const TextLanguage = (linguagem) => {
    return linguagem == "pt" ? {
        linguagem: "pt",
        ajuda: {
            ajuda: "Ajuda",
        },
        barraProgressaoDemanda: {
            steps: {
                dados: "Dados",
                beneficios: "Benefícios",
                anexos: "Anexos"
            },
            erroPularPasso: "Você não pode pular um passo que não é opcional!",
            botaoVoltar: "Voltar",
            botaoPular: "Pular",
            botaoCriar: "Criar",
            botaoProximo: "Próximo",
            mensagemFeedback: "Preencha todos os campos obrigatórios!"
        },
        barraProgressaoProposta: {
            botaoVoltar: "Voltar",
            botaoCriar: "Criar",
            botaoProximo: "Próximo",
        },
        beneficios: {
            beneficios: "Benefícios",
            real: "Real",
            potencial: "Potencial",
            qualitativo: "Qualitativo",
            valorMensal: "Valor Mensal",
            exemploValorMensal: "Ex: 1000,00",
            moeda: "Moeda",
            memoriaCalculo: "Memória de cálculo",
            digiteMemoriaCalculo: "Digite a memória de cálculo...",
        },
        BeneficiosDetalheDemanda: {
            tipo: "Tipo",
            valorMensal: "Valor Mensal",
            moeda: "Moeda",
            memoriaCalculo: "Memória de Cálculo",
            real: "Real",
            potencial: "Potencial",
            qualitativo: "Qualitativo",
            digiteValorMensal: "Digite o valor mensal...",
            digiteMemoriaCalculo: "Digite a memória de cálculo...",
        },
        caminho: {
            home: "Home",
        },
        chatMinimizado: {
            minimizar: "Minimizar",
            maximazar: "Maximizar",
            telaCheia: "Tela Cheia",
            fecharChat: "Fechar Chat",
            escrevaSuaMensagem: "Escreva sua mensagem...",
            enviarAnexo: "Enviar Anexo",
            enviarMensagem: "Enviar Mensagem",
        },
        containerPauta: {
            propostas: "Propostas",
        },
        contato: {
            demanda: "Demanda",
        },
        custos: {
            excluirTabelaDeCustos: "Excluir tabela de custos",
            tipoDaDespesa: "Tipo da Despesa",
            perfilDaDespesa: "Perfil da Despesa",
            periodoDeExecucao: "Período de Execução (Meses)",
            horas: "Horas",
            valorHora: "Valor Hora",
            total: "Total",
            h: "h",
            moeda: "R$",
            adicionarNovaLinha: "Adicionar nova linha",
            ccs: "CCs",
        },
        demanda: {
            status: {
                reprovada: "Reprovada",
                aguardandoRevisao: "Aguardando Revisão",
                aguardandoEdicao: "Aguardando Edição",
                emAprovacao: "Em Aprovação",
                aprovada: "Aprovada",
                emAndamento: "Em Andamento",
            },
            motivo: "Motivo",
        },
        demandaGerencia: {
            backlog: "Backlog",
            assessment: "Assessment",
            ppm: "PPM",
            solicitante: "Solicitante",
            departamento: "Departamento",
            naoAtribuido: "Não Atribuído",
            analistaResponsavel: "Analista Responsável",
            gerenteResponsavel: "Gerente Responsável",
            chat: "Chat",
            historico: "Histórico",
        },
        demandaGerenciaModoVisualizacao: {
            backlog: "Backlog",
            assessment: "Assessment",
            codigo: "Código",
            titulo: "Título",
            solicitante: "Solicitante",
            departamento: "Departamento",
            gerenteResponsavel: "Gerente Responsável",
            status: "Status",
            data: "Data",
            naoAtribuido: "Não atribuído",
            historico: "Histórico",
            chat: "Chat",
            proposta: "proposta",
            nadaEncontrado: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        demandaModoVisualizacao: {
            status: {
                reprovada: "Reprovada",
                aguardandoRevisao: "Aguardando Revisão",
                aguardandoEdicao: "Aguardando Edição",
                emAprovacao: "Em Aprovação",
                aprovada: "Aprovada",
                emAndamento: "Em Andamento",
            },
            codigo: "Código",
            titulo: "Titulo",
            status: "Status",
            data: "Data",
            motivo: "Motivo",
            nadaEncontrado: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        DetalhesDemanda: {
            real: "Real",
            facaAlgumaAlteracaoParaPoderSalvar: "Faça alguma alteração para poder salvar!",
            jaHaUmAnexoComEsseNome: "Já há um anexo com esse nome!",
            problema: "Problema",
            proposta: "Proposta",
            beneficios: "Benefícios",
            frequenciaDeUso: "Frequência de Uso",
            tamanho: "Tamanho",
            secaoDeTi: "Seção de TI",
            buSolicitante: "BU Solicitante",
            busBeneficiadas: "BUs Beneficiadas",
            forum: "Fórum",
            anexos: "Anexos",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
            digiteTituloDaDemanda: "Digite o título da demanda...",
            digiteProblema: "Digite o problema...",
            digiteProposta: "Digite a proposta...",
            digiteFrequenciaDeUso: "Digite a frequência de uso...",
            baixar: "Baixar",
            remover: "Remover",
            botaoRecusar: "Recusar",
            botaoDevolver: "Devolver",
            botaoAceitar: "Aceitar",
            botaoSalvar: "Salvar",
        },
        escopo: {
            titleExcluir: "Excluir",
        },
        formularioAnexosDemanda: {
            arrasteSolteParaAdicionarUmArquivo: "Arraste & Solte para Adicionar um Arquivo",
            solteParaAdicionarArquivo: "Solte para Adicionar um Arquivo",
            ou: "OU",
            pesquisarArquivos: "Pesquisar Arquivos",
            nome: "Nome",
            tipo: "Tipo",
            remover: "Remover",
        },
        formularioBeneficiosDemanda: {
            adicionar: "Adicionar",
        },
        formularioCustosProposta: {
            total: "Total",
            horas: "h",
            moeda: "R$",
            adicionarCustos: "Adicionar Custos",
        },
        formularioDadosDemanda: {
            titulo: "Título:",
            digiteTitulo: "Digite o título...",
            problema: "Problema:",
            digiteProblema: "Digite o problema...",
            proposta: "Proposta:",
            digiteProposta: "Digite a proposta...",
            frequenciaDeUso: "Frequencia de uso:",
            digiteFrequenciaDeUso: "Digite a frequencia de uso...",
        },
        formularioGeralProposta: {
            periodoDeExecucao: "Período de execução",
            digiteCodigo: "Digite o código...",
            a: "à",
            paybackSimples: "Payback simples",
            quantidade: "Qtd",
            dias: "Dias",
            semanas: "Semanas",
            meses: "Meses",
            codigoPpm: "Código PPM",
            linkDoJira: "Link do Jira",
            insiraLinkDoJira: "Insira o link do Jira...",
            responsavelResponsaveis: "Responsável/Responsáveis",
            titleAdicionarNovoResponsavel: "Adicionar um novo responsável",
            anexos: "Anexos",
            adicionarNovoAnexo: "Adicionar um novo anexo",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
        },
        formularioPropostaProposta: {
            digiteTituloDaDemanda: "Digite o título da demanda...",
            problema: "Problema",
            digiteProblema: "Digite o problema...",
            proposta: "Proposta",
            digiteProposta: "Digite a proposta...",
            beneficios: "Beneficios",
            frequenciaDeUso: "Frequência de uso",
            digiteFrequencia: "Digite a frequência...",
            labelTamanho: "Tamanho",
            muitoPequeno: "Muito Pequeno",
            pequeno: "Pequeno",
            medio: "Médio",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            nenhumaSecaoEncontrada: "Nenhuma seção encontrada",
            labelSecaoTi: "Seção TI",
            nenhumaBuEncontrada: "Nenhuma BU encontrada",
            buSolicitante: "BU Solicitante",
            labelBusBeneficiadas: "BUs Beneficiadas",
            selecioneUmaOuMaisBus: "Selecione uma ou mais BUs",
            nenhumForumEncontrado: "Nenhum fórum encontrado",
            labelForum: "Fórum",
            anexos: "Anexos",
            titleBaixar: "Baixar",
            titleRemover: "Remover",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
        },
        Header: {
            paginaInicial: "Página Inicial",
        },
        idiomaModal: {
            idiomas: "Idiomas",
        },
        linhaTabelaCcs: {
            titleExcluirLinha: "Excluir linha",
            digiteCodigo: "Digite o código...",
        },
        linhaTabelaCustos: {
            digiteTipo: "Digite o tipo...",
            digitePerfil: "Digite o perfil...",
            digitePeriodo: "Digite o período...",
            digiteHoras: "Digite as horas...",
            digiteValor: "Digite o valor...",
            titleExcluirLinha: "Excluir linha",
        },
        modalAceitarDemanda: {
            informacoes: "Informações",
            tamanho: "Tamanho",
            muitoPequeno: "Muito Pequeno",
            pequeno: "Pequeno",
            medio: "Médio",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            buSolicitante: "BU Solicitante",
            nenhumaBuEncontrada: "Nenhuma BU encontrada",
            busBeneficiadas: "BUs Beneficiadas",
            selecioneUmaOuMaisBus: "Selecione uma ou mais BUs",
            nenhumaSecaoEncontrada: "Nenhuma seção encontrada",
            secaoTi: "Seção TI",
            forum: "Fórum",
            nenhumForumEncontrado: "Nenhum fórum encontrado",
            anexos: "Anexos",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
            cancelar: "Cancelar",
            aceitar: "Aceitar",
        },
        modalConfirmacao: {
            mensagensModal: {
                descartarRascunho: "Deseja descartar o escopo?",
                sairCriacao: "Deseja sair da criação da demanda?",
                enviarDemanda: "Deseja criar a demanda?",
                sairSemSalvar: "Deseja sair sem salvar?",
                descartarProposta: "Deseja descartar a proposta?",
                cancelarEdicao: "Deseja descartar as alterações?",
                aceitarDemanda: "Deseja aceitar a demanda?",
                confirmarExclusao: "Tem certeza que deseja excluir?",
                fecharChat: "Deseja realmente fechar este chat?",
            },
            mensagensBotao: {
                sim: "Sim",
                enviar: "Enviar",
                criar: "Criar",
                aceitar: "Aceitar",
            },
            cancelar: "Cancelar",
        },
        modalFiltro: {
            status: "Status",
            labels: {
                aprovada: "Aprovada",
                reprovada: "Reprovada",
                aguardandoEdicao: "Aguardando Edição",
                aguardandoRevisao: "Aguardando Revisão",
                emAprovacao: "Em Aprovação",
                emAndamento: "Em Andamento",
            },
        },
        modalFiltroGerencia: {
            filtros: "Filtros",
            semResultados: "Sem Resultados",
            labelSolicitante: "Solicitante",
            forum: "Fórum",
            selecionar: "Selecionar",
            tamanho: "Tamanho",
            selecionar: "Selecionar",
            muitoPequeno: "Muito Pequeno",
            semResultados: "Sem Resultados",
            analistaResponsavel: "Analista Responsável",
            gerenteResponsavel: "Gerente Responsável",
            pequeno: "Pequeno",
            medio: "Médio",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            departamento: "Departamento",
            numero: "Número",
            limparFilros: "Limpar Filtros",
        },
        modalHistoricoDemanda: {
            historico: "Histórico",
        },
        modalInformarMotivo: {
            informarMotivo: "Informar Motivo",
            informeMotivo: "Informe o motivo...",
            confirmar: "Confirmar",
        },
        modalMotivoRecusa: {
            motivoDaRecusa: "Motivo da recusa",
        },
        modalOrdenacao: {
            score: "Score",
            maiorScore: "Maior Score",
            menorScore: "Menor Score",
            titulo: "Título",
            az: "A-Z",
            za: "Z-A",
            data: "Data",
            maisRecente: "Mais recente",
            maisAntiga: "Mais antiga",
        },
        modalRecusarDemanda: {
            motivoDaRecusa: "Motivo da recusa",
            informeMotivo: "Informe o motivo...",
            enviar: "Enviar",
        },
        notificacao: {
            diasAtras: "dias atrás",
            hoje: "hoje",
            umaSemanaAtras: "1 semana atrás",
            duasSemanasAtras: "2 semanas atrás",
            tresSemanasAtras: "3 semanas atrás",
            quatroSemanasAtras: "4 semanas atrás",
            maisDeUmMesAtras: "mais de 1 mês atrás",
        },
        notificacaoModal: {
            notificacaoLidaComSucesso: "Notificação lida com sucesso!",
            notificacoes: "Notificações",
            nenhumaNotificaçaoEncontrada: "Nenhuma notificação encontrada!",
            verTudo: "Ver tudo",
            verNotificacoes: "Ver notificações",
        },
        paginacao: {
            itensPorPagina: "Itens por página",
        },
        pauta: {
            deletar: "Deletar",
            comissao: "Comissão",
            analistaResponsavel: "Analista Responsável",
        },
        pautaAtaModoVisualizacao: {
            as: "às",
            numeroSequencial: "Num. Seq.",
            comissao: "Comissão",
            analistaResponsavel: "Anal. Resp.",
            deletar: "Deletar",
            data: "Data",
            nadaEncontrados: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        propostaDeAta: {
            codigoPpm: "Código PPM",
            tituloDaProposta: "Título da Proposta",
            responsavelDoNegocio: "Responsável do Negócio",
            problema: "Problema",
            proposta: "Proposta",
            beneficios: "Benefícios",
            frequenciaDeUso: "Frequência de Uso",
            custos: "Custos",
            custosAqui: "Custos aqui",
            periodoDeExecucao: "Período de Execução",
            paybackSimples: "Payback Simples",
            linkDoJira: "Link Do Jira",
            anexos: "Anexos",
            parecerComissao: "Parecer Comissão",
            maisInformacoes: "Mais Informações",
            businessCase: "Business Case",
            aprovado: "Aprovado",
            escrevaNovaInformacao: "Escreva a nova informação...",
            parecerDG: "Parecer DG",
            aprovado: "Aprovado",
            reprovado: "Reprovado",
        },
        responsavelNegocio: {
            responsavelDoNegocio: "Responsável do negócio",
            insiraResponsavelDoNegocio: "Insira o responsável pelo negócio...",
            area: "Área",
            insiraAreaDoResponsavel: "Insira a área do responsável...",
        },
        textEditor: {
            digiteAquiEscopoDaProposta: "Digite aqui o escopo da proposta...",
        },
        userModal: {
            normal: "Normal",
            pequeno: "Pequeno",
            muitoPequeno: "Muito Pequeno",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            configuracoes: "Configurações",
            escopos: "Escopos",
            chats: "Chats",
            A: "A",
            diminuirFonte: "Diminuir fonte",
            aumentarFonte: "Aumentar fonte",
            modoClaroEscuro: "Modo Claro/Escuro",
            sair: "Sair",
        },
        chat: {
            tour: {
                tour1: "Neste input você pode pesquisar pelos chats por nome do usuário e pelo número sequêncial da demanda.",
                tour2: "Aqui fica os chats abertos, tendo o nome do usuário, o número sequêncial da demanda e de qual demanda pertence.",
                tour3: "Neste botão pode escolher entre minimizar o chat ou encerrar a conversa (fechando o chat).",
                tour4: "Aqui pode escrever o que deseja enviar, podendo também anexar algum arquivo.",
            },
            pesquisarPorNome: "Pesquisar por nome...",
            usuarioTour: {
                tour: "Tour",
                gerente: "Gerente",
                mostrarNoTour: "Mostrar no tour",
                olaTudoBem: "Olá, tudo bem?",
                tudoSimVoce: "Tudo sim, e você? Estou aqui para te mostrar como funciona o chat.",
                eu: "Eu",
                bemTambemObrigado: "Bem também, obrigado.",
            },
            usuario: "Usuário",
            selecioneAlgumaConversa: "Selecione alguma conversa",
            miniChatAberto: "Mini chat aberto",
            opcoes: "Opções",
            abrirPopUp: "Abrir pop-up",
            encerrarChat: "Encerrar chat",
            escrevaSuaMensagem: "Escreva sua mensagem...",
            enviarAnexo: "Enviar anexo",
            enviarMensagem: "Enviar mensagem",
        },
        detalhesAta: {
            ataCriadaComSucesso: "Ata criada com sucesso!",
            ata: "Ata",
            numeroSequencial: "Número Sequencial",
            data: "Data",
            inicio: "Início",
            fim: "Fim",
            sumario: "Sumário",
            proposta: "Proposta",
            voltar: "Voltar",
            navegacao: "Navegação",
            publicarAta: "Publicar Ata",
            proximo: "Próximo",
            publicar: "Publicar",
        },
        detalhesDemandaPagina: {
            tour: {
                tour1: "Essa é a página de detalhes da demanda. Aqui você pode ver todos os detalhes da demanda selecionada.",
                tour2: "Cicando aqui, você consegue baixar em PDF essa demanda.",
                tour3: "Clicando neste lápis, você consegue estar editando as informações.",
            }
        },
        detalhesPauta: {
            baixarPDF: "Baixar PDF",
            pauta: "Pauta",
            numeroSequencial: "Número Sequencial",
            ano: "Ano",
            sumario: "Sumário",
            proposta: "Proposta",
            voltar: "Voltar",
            proximo: "Próximo",
            navegacao: "Navegação",
            criarAta: "Criar Ata",
        },
        detalhesPropostaPagina: {
            adicionarAPauta: "Adicionar à Pauta",
        },
        escopos: {
            tour: {
                tour1: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
                tour2: "Aqui fica os escopos criados automaticamente, em cada escopo é possível abrir novamente para edição. É criado um escopo para cada projeto que você abre e não finaliza.",
                tour3: "Nesta área você consegue visualizar qual a porcentagem preenchida do formulário.",
                tour4: "Clicando na lixeira você exclui o escopo.",
            },
            pesquisarPorTitulo: "Pesquisar por título...",
            pesquisar: "Pesquisar",
            escopoDeletadoComSucesso: "Escopo deletado com sucesso!",
        },
        home: {
            tourAjuda: {
                barraDePesquisa: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
                iconeOredenar: "Neste ícone você pode ordenar as suas demandas por título (A-Z ou Z-A), Score (Maior ao menor ou Menor ao maior) e pela data (Mais nova à mais velha ou Mais velha à Mais nova).",
                botaoFiltrar: "Neste botão você pode filtrar suas demandas por seus status.",
                modoVisualizacao: "Nesta parte você pode trocar o modo de visualização das suas demandas. Você pode escolher entre visualizar as demandas em forma de lista ou em forma de cards.",
                criarNovaDemanda: "Aqui você consegue iniciar a criação de uma nova demanda.",
                areaDemanda: "Nesta área você consegue observar suas demandas. Você pode clicar em uma demanda para ver mais detalhes.",
                statusDemanda: "Nesta área você consegue visualizar o status atual da demanda.",
                botaoMotivo: "Aqui consegue observar o motivo pelo qual foi recusado ou o motivo da edição.",
            },
            demandaCriadaComSucesso: "Demanda criada com sucesso!",
            minhasDemandas: "Minhas Demandas",
            meuDepartamento: "Meu Departamento",
            visualizacaoEmTabela: "Visualização em Tabela",
            visualizacaoEmBloco: "Visualização em Bloco",
            pesquisarPorTitulo: "Pesquisar por título...",
            pesquisar: "Pesquisar",
            ordenacao: "Ordenação",
            filtrar: "Filtrar",
            criarDemanda: "Criar Demanda",
            demandaTour: "Demanda Tour",
            esseUmExemploDeDemanda: "Esse é um exemplo de demanda",
            nomeDoSolicitante: "Nome do Solicitante",
        },
        homeGerencia: {
            toursDemandas: {
                tour1: "Aqui é a barra de pesquisa, você pode pesquisar por algum título de alguma demanda",
                tour2: "Esse é icone de ordenação, onde poderá ordenar os itens por ordem alfabética, por score ou por data de criação",
                tour3: "Aqui fica o filtro, podendo filtrar por: Solicitante, Gerente Responsável, Fórum, Departamento, Tamanho e número",
                tour4: "Aqui fica o lugar para exportar as demandas em formato de planilha",
                tour5: "Aqui pode iniciar o processo de criação de uma nova demanda",
                tour6: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes",
                tour7: "Clicando aqui você pode ver o histórico de alterações da demanda",
                tour8: "Nesta área você pode visualizar o status da demanda",
                tour9: "Clicando aqui você pode alterar o modo de visualização para tabela ou cards",
            },
            toursCriarPropostas: {
                tour1: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes e/ou criar uma proposta",
                tour2: "Nesta área você pode visualizar o status da demanda",
                tour3: "Clique aqui para ver o histórico de alterações da demanda",
            },
            toursPropostas: {
                tour1: "Nesta parte fica as propostas, podendo clicar em uma proposta para ver mais detalhes.",
                tour2: "Clicando aqui você pode abrir o chat com o solicitante da demanda",
                tour3: "Clicando aqui você pode ver o histórico de alterações da proposta",
            },
            toursPautas: {
                tour1: "Nesta parte fica as pautas, podendo clicar em uma pauta para ver mais detalhes.",
                tour2: "Clicando aqui você pode excluir a pauta",
            },
            toursAtas: {
                tour1: "Nesta parte fica as atas, podendo clicar em uma ata para ver mais detalhes",
            },
            feedback: {
                feedback1: "Ata publicada com sucesso!",
                feedback2: "Demanda aceita com sucesso!",
                feedback3: "Demanda recusada com sucesso!",
                feedback4: "Demanda devolvida com sucesso!",
                feedback5: "Proposta criada com sucesso!",
            },
            demandas: "Demandas",
            criarPropostas: "Criar Propostas",
            propostas: "Propostas",
            pautas: "Pautas",
            atas: "Atas",
            visualizacaoEmTabela: "Visualização em tabela",
            visualizacaoEmBloco: "Visualização em bloco",
            pesquisarPorTitulo: "Pesquisar por título...",
            pesquisar: "Pesquisar",
            ordenacao: "Ordenação",
            filtrar: "Filtrar",
            exportar: "Exportar",
            criarDemanda: "Criar Demanda",
            demandaParaTour: "Demanda para Tour",
        },
        login: {
            email: "Email",
            senha: "Senha",
            esqueciSenha: "Esqueci a senha",
            entrar: "Entrar",
            feedback: {
                dadosInvalidos: "Dados inválidos!",
                preenchaTodosOsCampos: "Preencha todos os campos!",
            },
        },
        notFound: {
            paginaNaoEncontrada: "Página não encontrada!",
            desculpePaginaNaoEncontrada: "Desculpe, a página informada não foi encontrada!",
            porfavorVolteParaPaginaPrincipal: "Por favor, volte para a página principal.",
            voltar: "Voltar",
        },
        notificacao: {
            notificacaoMArcadasComoNaoLidasComSucesso: "Notificações marcadas como não lidas com sucesso!",
            notificacaoMArcadasComoLidasComSucesso: "Notificações marcadas como lidas com sucesso!",
            notificacaoExcluidasComSucesso: "Notificações excluídas com sucesso!",
            notificacoes: "Notificações",
            deletar: "Deletar",
            marcarComoLido: "Marcar como lido",
            tipo: "Tipo",
            titulo: "Titulo",
            data: "Data",
            marcarComoNaoLido: "Marcar como não lido",
            marcarCommoLido: "Marcar como lido",
            naoHaNotificacoes: "Não há notificações",
        },
        detalhesProposta: {
            ppm: "PPM",
            solicitante: "Solicitante",
            objetivo: "Objetivo",
            proposta: "Proposta",
            problema: "Problema",
            escopoDaProposta: "Escopo da Proposta",
            periodoDeExecucao: "Período de Execução",
            payback: "Payback",
            reponsaveisPeloNegocio: "Responsáveis pelo Negócio",
            ate: "até",
            tabelaDeCustos: "Tabela de Custos",
            tipoDaDespesa: "Tipo da Despesa",
            perfilDaDespesa: "Perfil da Despesa",
            periodoDeExecucaoTabela: "Período de Execução (meses)",
            horas: "Horas",
            valorHora: "Valor Hora",
            total: "Total",
            ccs: "CCs",
            porcentagem: "Porcentagem",
            anexos: "Anexos",
            download: "Baixar",
            semAnexos: "Proposta sem anexos",
            beneficios: "Benefícios",
            semBeneficios: "Proposta sem benefícios",
            tipoBeneficio: "Tipo",
            valorMensal: "Valor Mensal",
            moeda: "Moeda",
            memoriaCalculo: "Memória de Cálculo",
            busBeneficiadas: "BUs Beneficiadas",
            semBuBeneficiada: "Proposta sem BUs beneficiadas",
            buSolicitante: "BU Solicitante",
            frequencia: "Frequência",
            linkJira: "Link Jira",
            tamanho: "Tamanho",
            data: "DATA",
            gerente: "Gerente",
            pareceres: "Pareceres",
            forum: "Fórum",
            aprovado: "Aprovado",
            reprovado: "Reprovado",
            devolvido: "Devolvido",
            businessCase: "Business Case",
            parecer: "Parecer",
            maisInformacoes: "Mais Informações...",
            comissao: "Comissão",
            direcaoGeral: "Direção Geral",
            semInformacoesAdicionais: "Sem informações adicionais",
            semParecer: "Sem parecer",
        },
        modalAddPropostaPauta: {
            selecioneAPauta: "Selecione a pauta",
            propostas: "Propostas",
            comissao: "Comissão",
            adicionarComoProposta: "Adicionar como proposta",
            publicada: "Publicada",
            naoPublicada: "Não publicada",
            novaPauta: "Nova Pauta",
            adicionar: "Adicionar",
            numSequencial: "Nº Sequencial",
            essaPropostaJaSeEncontraEmUmaPauta: "Essa proposta já se encontra em uma pauta!",
        }

    } : linguagem == "en" ? {
        linguagem: "en",
        ajuda: {
            ajuda: "Help",
        },
        barraProgressaoDemanda: {
            steps: {
                dados: "Data",
                beneficios: "Benefits",
                anexos: "Attachments",
            },
            erroPularPasso: "You cannot skip a step that is not optional!",
            botaoVoltar: "Back",
            botaoPular: "Skip",
            BotaoCriar: "Create",
            botaoProximo: "Next",
            mensagemFeedback: "You must fill in all the fields!",
        },
        barraProgressaoProposta: {
            botaoVoltar: "Back",
            botaoCriar: "Create",
            botaoProximo: "Next",
        },
        beneficios: {
            beneficios: "Benefits",
            real: "Real",
            potencial: "Potential",
            qualitativo: "Qualitative",
            valorMensal: "Monthly Value",
            exemploValorMensal: "E.g: 1000,00",
            moeda: "Currency",
            memoriaCalculo: "Calculation memory",
            digiteMemoriaCalculo: "Enter the calculation memory...",
        },
        BeneficiosDetalheDemanda: {
            tipo: "Type",
            valorMensal: "Monthly Value",
            moeda: "Currency",
            memoriaCalculo: "Calculation memory",
            real: "Real",
            potencial: "Potential",
            qualitativo: "Qualitative",
            digiteValorMensal: "Enter the monthly value...",
            digiteMemoriaCalculo: "Enter the calculation memory...",
        },
        caminho: {
            home: "Home",
        },
        chatMinimizado: {
            minimizar: "Minimize",
            maximazar: "Maximize",
            telaCheia: "Full screen",
            fecharChat: "Close Chat",
            escrevaSuaMensagem: "Write your message...",
            enviarAnexo: "Send Attachment",
            enviarMensagem: "Send Message",
        },
        containerPauta: {
            propostas: "Proposals",
        },
        contato: {
            demanda: "Demand",
        },
        custos: {
            excluirTabelaDeCustos: "Delete cost table",
            tipoDaDespesa: "Expense Type",
            perfilDaDespesa: "Expense Profile",
            periodoDeExecucao: "Execution Period (Months)",
            horas: "Hours",
            valorHora: "Hour Value",
            total: "Total",
            moeda: "R$",
            adicionarNovaLinha: "Add new line",
            ccs: "CCs",
        },
        demanda: {
            status: {
                reprovada: "Rejected",
                aguardandoRevisao: "Awaiting Review",
                aguardandoEdicao: "Awaiting Edition",
                emAprovacao: "In Approval",
                aprovada: "Approved",
                emAndamento: "In Progress",
            },
            motivo: "Reason",
        },
        demandaGerencia: {
            backlog: "Backlog",
            assessment: "Assessment",
            ppm: "PPM",
            solicitante: "Requester",
            departamento: "Department",
            naoAtribuido: "Not assigned",
            analistaResponsavel: "Responsible Analyst",
            gerenteResponsavel: "Responsible Manager",
            chat: "Chat",
            historico: "History",
        },
        demandaGerenciaModoVisualizacao: {
            backlog: "Backlog",
            assessment: "Assessment",
            codigo: "Code",
            titulo: "Title",
            solicitante: "Requester",
            departamento: "Department",
            gerenteResponsavel: "Responsible Manager",
            status: "Status",
            data: "Date",
            naoAtribuido: "Not assigned",
            historico: "History",
            chat: "Chat",
            nadaEncontrado: "Nothing found",
            tenteNovamenteMaisTarde: "Try again later",
        },
        demandaModoVisualizacao: {
            status: {
                reprovada: "Rejected",
                aguardandoRevisao: "Awaiting Review",
                aguardandoEdicao: "Awaiting Edition",
                emAprovacao: "In Approval",
                aprovada: "Approved",
                emAndamento: "In Progress",
            },
            codigo: "Code",
            titulo: "Title",
            status: "Status",
            data: "Date",
            motivo: "Reason",
            nadaEncontrado: "Nothing found",
            tenteNovamenteMaisTarde: "Try again later",
        },
        DetalhesDemanda: {
            facaAlgumaAlteracaoParaPoderSalvar: "Make some changes to be able to save!",
            jaHaUmAnexoComEsseNome: "There is already an attachment with that name!",
            problema: "Problem",
            proposta: "Proposal",
            beneficios: "Benefits",
            frequenciaDeUso: "Frequency of Use",
            tamanho: "Size",
            secaoDeTi: "IT Section",
            buSolicitante: "Requesting BU",
            busBeneficiadas: "Benefited BUs",
            forum: "Forum",
            anexos: "Attachments",
            nenhumAnexoAdicionado: "No attachments added",
            digiteTituloDaDemanda: "Enter the title of the demand...",
            digiteProblema: "Enter the problem...",
            digiteProposta: "Enter the proposal...",
            digiteFrequenciaDeUso: "Enter the frequency of use...",
            baixar: "Download",
            remover: "Remove",
            botaoRecusar: "Reject",
            botaoDevolver: "Return",
            botaoAceitar: "Accept",
            botaoSalvar: "Save",
        },
        escopo: {
            titleExcluir: "Delete",
        },
        formularioAnexosDemanda: {
            arrasteSolteParaAdicionarUmArquivo: "Drag & Drop to Add a File",
            solteParaAdicionarArquivo: "Drop to Add a File",
            ou: "OR",
            pesquisarArquivos: "Search Files",
            nome: "Name",
            tipo: "Type",
            remover: "Remove",
        },
        formularioBeneficiosDemanda: {
            adicionar: "Add",
        },
        formularioCustosProposta: {
            total: "Total",
            horas: "h",
            moeda: "$",
            adicionarCustos: "Add Costs",
        },
        formularioDadosDemanda: {
            titulo: "Title:",
            digiteTitulo: "Enter the title...",
            problema: "Problem:",
            digiteProblema: "Enter the problem...",
            proposta: "Proposal:",
            digiteProposta: "Enter the proposal...",
            frequenciaDeUso: "Frequency of Use:",
            digiteFrequenciaDeUso: "Enter the frequency of use...",
        },
        formularioGeralProposta: {
            periodoDeExecucao: "Execution Period",
            digiteCodigo: "Enter the code...",
            a: "to",
            paybackSimples: "Simple Payback",
            quantidade: "Qty",
            dias: "Days",
            semanas: "Weeks",
            meses: "Months",
            codigoPpm: "PPM Code",
            linkDoJira: "Jira Link",
            insiraLinkDoJira: "Enter the Jira link...",
            responsavelResponsaveis: "Responsible/Responsibles",
            titleAdicionarNovoResponsavel: "Add a new responsible",
            anexos: "Attachments",
            adicionarNovoAnexo: "Add a new attachment",
            nenhumAnexoAdicionado: "No attachments added",
        },
        formularioPropostaProposta: {
            digiteTituloDaDemanda: "Enter the title of the demand...",
            problema: "Problem",
            digiteProblema: "Enter the problem...",
            proposta: "Proposal",
            digiteProposta: "Enter the proposal...",
            beneficios: "Benefits",
            frequenciaDeUso: "Frequency of Use",
            digiteFrequencia: "Enter the frequency...",
            labelTamanho: "Size",
            muitoPequeno: "Very Small",
            pequeno: "Small",
            medio: "Medium",
            grande: "Large",
            muitoGrande: "Very Large",
            nenhumaSecaoEncontrada: "No section found",
            labelSecaoTi: "IT Section",
            nenhumaBuEncontrada: "No BU found",
            buSolicitante: "Requesting BU",
            labelBusBeneficiadas: "Benefited BUs",
            selecioneUmaOuMaisBus: "Select one or more BUs",
            nenhumForumEncontrado: "No forum found",
            labelForum: "Forum",
            anexos: "Attachments",
            titleBaixar: "Download",
            titleRemover: "Remove",
            nenhumAnexoAdicionado: "No attachments added",
        },
        Header: {
            paginaInicial: "Home",
        },
        idiomaModal: {
            idiomas: "Languages",
        },
        linhaTabelaCcs: {
            titleExcluirLinha: "Delete line",
            digiteCodigo: "Enter the code...",
        },
        linhaTabelaCustos: {
            digiteTipo: "Enter the type...",
            digitePerfil: "Enter the profile...",
            digitePeriodo: "Enter the period...",
            digiteHoras: "Enter the hours...",
            digiteValor: "Enter the value...",
            titleExcluirLinha: "Delete line",
        },
        modalAceitarDemanda: {
            informacoes: "Information",
            tamanho: "Size",
            muitoPequeno: "Very Small",
            pequeno: "Small",
            medio: "Medium",
            grande: "Large",
            muitoGrande: "Very Large",
            buSolicitante: "Requesting BU",
            nenhumaBuEncontrada: "No BU found",
            busBeneficiadas: "Benefited BUs",
            selecioneUmaOuMaisBus: "Select one or more BUs",
            nenhumaSecaoEncontrada: "No section found",
            secaoTi: "IT Section",
            forum: "Forum",
            nenhumForumEncontrado: "No forum found",
            anexos: "Attachments",
            nenhumAnexoAdicionado: "No attachments added",
            cancelar: "Cancel",
            aceitar: "Accept",
        },
        modalConfirmacao: {
            mensagensModal: {
                descartarRascunho: "Do you want to discard the scope?",
                sairCriacao: "Do you want to leave the demand creation?",
                enviarDemanda: "Do you want to create the demand?",
                sairSemSalvar: "Do you want to leave without saving?",
                descartarProposta: "Do you want to discard the proposal?",
                cancelarEdicao: "Do you want to discard the changes?",
                aceitarDemanda: "Do you want to accept the demand?",
                confirmarExclusao: "Are you sure you want to delete?",
                fecharChat: "Do you really want to close this chat?",
            },
            mensagensBotao: {
                sim: "Yes",
                enviar: "Send",
                criar: "Create",
                aceitar: "Accept",
            },
            cancelar: "Cancel",
        },
        modalFiltro: {
            status: "Status",
            labels: {
                aprovada: "Approved",
                reprovada: "Disapproved",
                aguardandoEdicao: "Waiting for Edition",
                aguardandoRevisao: "Waiting for Review",
                emAprovacao: "In Approval",
                emAndamento: "In Progress",
            },
        },
        modalFiltroGerencia: {
            filtros: "Filters",
            semResultados: "No results found",
            labelSolicitante: "Requester",
            forum: "Forum",
            selecionar: "Select",
            tamanho: "Size",
            semResultados: "No results found",
            analistaResponsavel: "Responsible Analyst",
            gerenteResponsavel: "Responsible Manager",
            muitoPequeno: "Very Small",
            pequeno: "Small",
            medio: "Medium",
            grande: "Large",
            muitoGrande: "Very Large",
            departamento: "Department",
            numero: "Number",
            limparFilros: "Clear Filters",
        },
        modalHistoricoDemanda: {
            historico: "History",
        },
        modalInformarMotivo: {
            informarMotivo: "Inform Reason",
            informeMotivo: "Enter the reason...",
            confirmar: "Confirm",
        },
        modalMotivoRecusa: {
            motivoDaRecusa: "Reason for refusal",
        },
        modalOrdenacao: {
            score: "Score",
            maiorScore: "Highest Score",
            menorScore: "Lowest Score",
            titulo: "Title",
            az: "A-Z",
            za: "Z-A",
            data: "Date",
            maisRecente: "Most recent",
            maisAntiga: "Oldest",
        },
        modalRecusarDemanda: {
            motivoDaRecusa: "Reason for refusal",
            informeMotivo: "Enter the reason...",
            enviar: "Send",
        },
        notificacao: {
            diasAtras: "days ago",
            hoje: "today",
            umaSemanaAtras: "1 week ago",
            duasSemanasAtras: "2 weeks ago",
            tresSemanasAtras: "3 weeks ago",
            quatroSemanasAtras: "4 weeks ago",
            umMesAtras: "1 month ago",
        },
        notificacaoModal: {
            notificacaoLidaComSucesso: "Notification read successfully!",
            notificacoes: "Notifications",
            nenhumaNotificaçaoEncontrada: "No notification found!",
            verTudo: "See all",
            verNotificacoes: "See notifications",
        },
        paginacao: {
            itensPorPagina: "Items per page",
        },
        pauta: {
            deletar: "Delete",
            comissao: "Commission",
            analistaResponsavel: "Responsible Analyst",
        },
        pautaAtaModoVisualizacao: {
            as: "to",
            numeroSequencial: "Seq. Num.",
            comissao: "Commission",
            analistaResponsavel: "Respon. Anal.",
            deletar: "Delete",
            data: "Date",
            nadaEncontrados: "Nothing found",
            tenteNovamenteMaisTarde: "Try again later",
        },
        propostaDeAta: {
            codigoPpm: "PPM Code",
            tituloDaProposta: "Proposal Title",
            responsavelDoNegocio: "Business Responsible",
            problema: "Problem",
            proposta: "Proposal",
            beneficios: "Benefits",
            frequenciaDeUso: "Frequency of Use",
            custos: "Costs",
            custosAqui: "Costs here",
            periodoDeExecucao: "Execution Period",
            paybackSimples: "Simple Payback",
            linkDoJira: "Jira Link",
            anexos: "Attachments",
            parecerComissao: "Commission Opinion",
            maisInformacoes: "More Information",
            businessCase: "Business Case",
            escrevaNovaInformacao: "Write new information...",
            parecerDG: "DG Opinion",
            aprovado: "Approved",
            reprovado: "Disapproved",
        },
        responsavelNegocional: {
            responsavelDoNegocio: "Business Responsible",
            insiraResponsavelDoNegocio: "Enter the business responsible...",
            area: "Area",
            insiraAreaDoResponsavel: "Enter the responsible area...",
        },
        textEditor: {
            digiteAquiEscopoDaProposta: "Enter here the proposal scope...",
        },
        userModal: {
            normal: "Normal",
            pequeno: "Small",
            muitoPequeno: "Very Small",
            grande: "Large",
            muitoGrande: "Very Large",
            configuracoes: "Settings",
            escopos: "Drafts",
            chats: "Chats",
            A: "A",
            diminuirFonte: "Decrease font",
            aumentarFonte: "Increase font",
            modoClaroEscuro: "Light/Dark Mode",
            sair: "Exit",
        },
        chat: {
            tour: {
                tour1: "In this input you can search for chats by user name and by the sequential number of the demand.",
                tour2: "Here are the open chats, having the user name, the sequential number of the demand and from which demand it belongs.",
                tour3: "In this button you can choose between minimizing the chat or ending the conversation (closing the chat).",
                tour4: "Here you can write what you want to send, you can also attach a file.",
            },
            pesquisarPorNome: "Search by name...",
            usuarioTour: {
                tour: "Tour",
                gerente: "Manager",
                mostrarNoTour: "Show in tour",
                olaTudoBem: "Hello, how are you?",
                tudoSimVoce: "Fine, and you?",
                eu: "Me",
                bemTambemObrigado: "Fine, thank you!",
            },
            usuario: "User",
            selecioneAlgumaConversa: "Select some conversation",
            miniChatAberto: "Mini chat opened",
            opcoes: "Options",
            abrirPopUp: "Open pop-up",
            encerrarChat: "Close chat",
            escrevaSuaMensagem: "Write your message...",
            enviarAnexo: "Send attachment",
            enviarMensagem: "Send message",
        },
        detalhesAta: {
            ataCriadaComSucesso: "Minutes created successfully!",
            ata: "Minutes",
            numeroSequencial: "Seq. Num.",
            data: "Date",
            inicio: "Start",
            fim: "End",
            sumario: "Summary",
            proposta: "Proposal",
            voltar: "Back",
            navegacao: "Navigation",
            publicarAta: "Publish Minutes",
            proximo: "Next",
            publicar: "Publish",
        },
        detalhesDemandaPagina: {
            tour: {
                tour1: "This is the demand details page. Here you can see all the details of the selected demand.",
                tour2: "By clicking here, you can download this demand in PDF format.",
                tour3: "By clicking on this pencil, you can edit this demand.",
            }
        },
        detalhesPauta: {
            baixarPDF: "PDF Download",
            pauta: "Minutes",
            numeroSequencial: "Seq. Num.",
            ano: "Year",
            sumario: "Summary",
            proposta: "Proposal",
            voltar: "Back",
            proximo: "Next",
            navegacao: "Navigation",
            criarAta: "Create Minutes",
        },
        escopos: {
            tour: {
                tour1: "Here is the search bar, where you can search by a title.",
                tour2: "Here are the automatically created scopes, in each scope it is possible to open again for editing. A scope is created for each project you open and do not finish.",
                tour3: "In this area you can see what percentage of the form is filled in.",
                tour4: "By clicking on the trash can you delete the scope.",
            },
            pesquisarPorTitulo: "Search by title...",
            pesquisar: "Search",
            escopoDeletadoComSucesso: "Scope deleted successfully!",
        },
        home: {
            tourAjuda: {
                barraDePesquisa: "Here is the search bar, where you can search by a title.",
                iconeOredenar: "In this icon you can order your demands by title (A-Z or Z-A), Score (Highest to lowest or lowest to highest) and by date (Newest to oldest or oldest to newest).",
                botaoFiltrar: "In this button you can filter your demands by their status.",
                modoVisualizacao: "In this part you can change the way you view your demands. You can choose between viewing the demands in the form of a list or in the form of cards.",
                criarNovaDemanda: "Here you can start creating a new demand.",
                areaDemanda: "In this area you can see your demands. You can click on a demand to see more details.",
                statusDemanda: "Here you can see the status of your demand.",
                botaoMotivo: "Here you can see the reason why it was rejected or the reason for the edit.",
            },
            demandaCriadaComSucesso: "Demand created successfully!",
            minhasDemandas: "My Demands",
            meuDepartamento: "My Department",
            visualizacaoEmTabela: "Table View",
            visualizacaoEmBloco: "Block View",
            pesquisarPorTitulo: "Search by title...",
            pesquisar: "Search",
            ordenacao: "Order",
            filtrar: "Filter",
            criarDemanda: "Create Demand",
            demandaTour: "Demand Tour",
            esseUmExemploDeDemanda: "This is an example of a demand.",
            esseUmExemploDeDemanda: "This is an example of a demand",
            nomeDoSolicitante: "Requester Name",
        },
        homeGerencia: {
            toursDemandas: {
                tour1: "Here is the search bar, where you can search by a title of a demand.",
                tour2: "This is the sorting icon, where you can order the items alphabetically, by score or by creation date.",
                tour3: "Here is the filter, where you can filter by: Requester, Responsible Manager, Forum, Department, Size and number.",
                tour4: "Here is the place to export the demands in spreadsheet format.",
                tour5: "Here you can start the process of creating a new demand.",
                tour6: "In this area are the demands, where you can click on a demand to see more details.",
                tour7: "By clicking here you can see the demand's history of changes.",
                tour8: "In this area you can see the status of the demand.",
                tour9: "By clicking here you can change the way you view the demands to table or cards.",
            },
            toursCriarPropostas: {
                tour1: "In this area are the demands, where you can click on a demand to see more details and/or create a proposal.",
                tour2: "In this area you can see the demand's status.",
                tour3: "By clicking here you can see the demand's history of changes.",
            },
            toursPropostas: {
                tour1: "In this area are the proposals, where you can click on a proposal to see more details.",
                tour2: "By clicking here you can open the chat with the demand requester.",
                tour3: "By clicking here you can see the proposal's history of changes.",
            },
            toursPautas: {
                tour1: "In this part are the minutes, where you can click on a minute to see more details.",
                tour2: "By clicking here you can delete the minute.",
            },
            toursAtas: {
                tour1: "In this part are the minutes, where you can click on a minute to see more details.",
            },
            feedback: {
                feedback1: "Minutes published successfully!",
                feedback2: "Demand accepted successfully!",
                feedback3: "Demand rejected successfully!",
                feedback4: "Demand returned successfully!",
                feedback5: "Proposal created successfully!",
            },
            demandas: "Demands",
            criarPropostas: "Create Proposals",
            propostas: "Proposals",
            pautas: "Agendas",
            atas: "Guidelines",
            visualizacaoEmTabela: "Table View",
            visualizacaoEmBloco: "Block View",
            pesquisarPorTitulo: "Search by title...",
            pesquisar: "Search",
            ordenacao: "Order",
            filtrar: "Filter",
            exportar: "Export",
            criarDemanda: "Create Demand",
            demandaParaTour: "Demand Tour",
        },
        login: {
            email: "Email",
            senha: "Password",
            esqueciSenha: "Forgot Password",
            entrar: "Login",
            feedback: {
                dadosInvalidos: "Invalid data!",
                preenchaTodosOsCampos: "Fill in all fields!",
            },
        },
        notFound: {
            paginaNaoEncontrada: "Page Not Found!",
            desculpePaginaNaoEncontrada: "Sorry, the page you requested was not found!",
            porfavorVolteParaPaginaPrincipal: "Please, return to the main page.",
            voltar: "Back",
        },
        notificacao: {
            notificacaoMArcadasComoNaoLidasComSucesso: "Notifications marked as unread successfully!",
            notificacaoMArcadasComoLidasComSucesso: "Notifications marked as read successfully!",
            notificacaoExcluidasComSucesso: "Notifications deleted successfully!",
            notificacoes: "Notifications",
            deletar: "Delete",
            marcarComoLido: "Mark as read",
            tipo: "Type",
            titulo: "Title",
            data: "Date",
            marcarComoNaoLido: "Mark as unread",
            marcarCommoLido: "Mark as read",
            deletar: "Delete",
            naoHaNotificacoes: "There are no notifications",
        },
        detalhesProposta: {
            ppm: "PPM",
            solicitante: "Requester",
            objetivo: "Objective",
            proposta: "Proposal",
            problema: "Problem",
            escopoDaProposta: "Proposal Scope",
            periodoDeExecucao: "Execution Period",
            payback: "Payback",
            reponsaveisPeloNegocio: "Business Responsible",
            ate: "to",
            tabelaDeCustos: "Cost Table",
            tipoDaDespesa: "Expense Type",
            perfilDaDespesa: "Expense Profile",
            periodoDeExecucaoTabela: "Execution Period (months)",
            horas: "Hours",
            valorHora: "Hour Value",
            total: "Total",
            ccs: "CCs",
            porcentagem: "Percentage",
            anexos: "Attachments",
            download: "Download",
            semAnexos: "Proposal without attachments",
            beneficios: "Benefits",
            semBeneficios: "Proposal without benefits",
            tipoBeneficio: "Type",
            valorMensal: "Monthly Value",
            moeda: "Currency",
            memoriaCalculo: "Calculation Memory",
            busBeneficiadas: "Benefited BUs",
            semBuBeneficiada: "Proposal without benefited BUs",
            buSolicitante: "Requester BU",
            frequencia: "Frequency",
            linkJira: "Jira Link",
            tamanho: "Size",
            data: "DATE",
            gerente: "Manager",
            pareceres: "Opinions",
            forum: "Forum",
            aprovado: "Approved",
            reprovado: "Disapproved",
            devolvido: "Returned",
            businessCase: "Business Case",
            parecer: "Opinion",
        },
        modalAddPropostaPauta: {
            selecioneAPauta: "Select a minute",
            propostas: "Proposals",
            comissao: "Commission",
            adicionarComoProposta: "Add as proposal",
            publicada: "Published",
            naoPublicada: "Not published",
            novaPauta: "New Minute",
            adicionar: "Add",
            numSequencial: "Seq. Number",
            essaPropostaJaSeEncontraEmUmaPauta: "This proposal is already in a minute!",
        }
    } : linguagem == "ch" ? {
        linguagem: "ch",
        ajuda: {
            ajuda: "帮助",
        },
        barraProgressaoDemanda: {
            steps: {
                dados: "数据",
                beneficios: "好处",
                anexos: "附件",
            },
            erroPularPasso: "您不能跳过一个不可选的步骤！",
            botaoVoltar: "背部",
            botaoPular: "跳过",
            BotaoCriar: "创建",
            botaoProximo: "下一个",
            mensagemFeedback: "您必须填写所有字段！",
        },
        barraProgressaoProposta: {
            botaoVoltar: "背部",
            botaoCriar: "创建",
            botaoProximo: "下一个",
        },
        beneficios: {
            beneficios: "好处",
            real: "真实",
            potencial: "潜在",
            qualitativo: "定性",
            valorMensal: "每月价值",
            exemploValorMensal: "例如：1000,00",
            moeda: "货币",
            memoriaCalculo: "计算记忆",
            digiteMemoriaCalculo: "输入计算记忆...",
        },
        BeneficiosDetalheDemanda: {
            tipo: "类型",
            valorMensal: "每月价值",
            moeda: "货币",
            memoriaCalculo: "计算记忆",
            real: "真实",
            potencial: "潜在",
            qualitativo: "定性",
            digiteValorMensal: "输入每月价值...",
            digiteMemoriaCalculo: "输入计算记忆...",
        },
        caminho: {
            home: "家",
        },
        chatMinimizado: {
            minimizar: "最小化",
            maximazar: "最大化",
            telaCheia: "全屏",
            fecharChat: "关闭聊天",
            escrevaSuaMensagem: "写下你的信息...",
            enviarAnexo: "发送附件",
            enviarMensagem: "发送信息",
        },
        containerPauta: {
            propostas: "提案",
        },
        contato: {
            demanda: "需求",
        },
        custos: {
            excluirTabelaDeCustos: "删除成本表",
            tipoDaDespesa: "费用类型",
            perfilDaDespesa: "费用配置文件",
            periodoDeExecucao: "执行期（月）",
            horas: "小时",
            valorHora: "每小时价值",
            total: "总",
            moeda: "¥",
            adicionarNovaLinha: "添加新行",
            ccs: "CCs",
        },
        demanda: {
            status: {
                reprovada: "拒绝",
                aguardandoRevisao: "等待审查",
                aguardandoEdicao: "等待编辑",
                emAprovacao: "正在批准",
                aprovada: "批准",
                emAndamento: "进行中",
            },
            motivo: "原因",
        },
        demandaGerencia: {
            backlog: "待办事项",
            assessment: "评估",
            ppm: "PPM",
            solicitante: "请求者",
            departamento: "部门",
            naoAtribuido: "未分配",
            analistaResponsavel: "负责分析师",
            gerenteResponsavel: "负责经理",
            chat: "聊天",
            historico: "历史",
        },
        demandaGerenciaModoVisualizacao: {
            backlog: "待办事项",
            assessment: "评估",
            codigo: "代码",
            titulo: "标题",
            solicitante: "请求者",
            departamento: "部门",
            gerenteResponsavel: "负责经理",
            status: "状态",
            data: "日期",
            naoAtribuido: "未分配",
            historico: "历史",
            chat: "聊天",
            nadaEncontrado: "没有找到",
            tenteNovamenteMaisTarde: "稍后再试",
        },
        demandaModoVisualizacao: {
            status: {
                reprovada: "拒绝",
                aguardandoRevisao: "等待审查",
                aguardandoEdicao: "等待编辑",
                emAprovacao: "正在批准",
                aprovada: "批准",
                emAndamento: "进行中",
            },
            codigo: "代码",
            titulo: "标题",
            status: "状态",
            data: "日期",
            motivo: "原因",
            nadaEncontrado: "没有找到",
            tenteNovamenteMaisTarde: "稍后再试",
        },
        DetalhesDemanda: {
            facaAlgumaAlteracaoParaPoderSalvar: "做一些更改才能保存！",
            jaHaUmAnexoComEsseNome: "已经有一个附件有这个名字！",
            problema: "问题",
            proposta: "提案",
            beneficios: "好处",
            frequenciaDeUso: "使用频率",
            tamanho: "大小",
            secaoDeTi: "IT部门",
            buSolicitante: "请求BU",
            busBeneficiadas: "受益BU",
            forum: "论坛",
            anexos: "附件",
            nenhumAnexoAdicionado: "没有添加附件",
            digiteTituloDaDemanda: "输入需求标题...",
            digiteProblema: "输入问题...",
            digiteFrequenciaDeUso: "输入使用频率...",
            baixar: "下载",
            remover: "删除",
            botaoRecusar: "拒绝",
            botaoDevolver: "返回",
            botaoAceitar: "接受",
            botaoSalvar: "保存",
        },
        escopo: {
            titleExcluir: "删除",
        },
        formularioAnexosDemanda: {
            arrasteSolteParaAdicionarUmArquivo: "拖放以添加文件",
            solteParaAdicionarArquivo: "放下以添加文件",
            ou: "或",
            pesquisarArquivos: "搜索文件",
            nome: "名称",
            tipo: "类型",
            remover: "删除",
        },
            

        
        // formularioBeneficiosDemanda: {
        //     adicionar: "Add",
        // },
        // formularioCustosProposta: {
        //     total: "Total",
        //     horas: "h",
        //     moeda: "$",
        //     adicionarCustos: "Add Costs",
        // },
        // formularioDadosDemanda: {
        //     titulo: "Title:",
        //     digiteTitulo: "Enter the title...",
        //     problema: "Problem:",
        //     digiteProblema: "Enter the problem...",
        //     proposta: "Proposal:",
        //     digiteProposta: "Enter the proposal...",
        //     frequenciaDeUso: "Frequency of Use:",
        //     digiteFrequenciaDeUso: "Enter the frequency of use...",
        // },
        // formularioGeralProposta: {
        //     periodoDeExecucao: "Execution Period",
        //     digiteCodigo: "Enter the code...",
        //     a: "to",
        //     paybackSimples: "Simple Payback",
        //     quantidade: "Qty",
        //     dias: "Days",
        //     semanas: "Weeks",
        //     meses: "Months",
        //     codigoPpm: "PPM Code",
        //     linkDoJira: "Jira Link",
        //     insiraLinkDoJira: "Enter the Jira link...",
        //     responsavelResponsaveis: "Responsible/Responsibles",
        //     titleAdicionarNovoResponsavel: "Add a new responsible",
        //     anexos: "Attachments",
        //     adicionarNovoAnexo: "Add a new attachment",
        //     nenhumAnexoAdicionado: "No attachments added",
        // },
        // formularioPropostaProposta: {
        //     digiteTituloDaDemanda: "Enter the title of the demand...",
        //     problema: "Problem",
        //     digiteProblema: "Enter the problem...",
        //     proposta: "Proposal",
        //     digiteProposta: "Enter the proposal...",
        //     beneficios: "Benefits",
        //     frequenciaDeUso: "Frequency of Use",
        //     digiteFrequencia: "Enter the frequency...",
        //     labelTamanho: "Size",
        //     muitoPequeno: "Very Small",
        //     pequeno: "Small",
        //     medio: "Medium",
        //     grande: "Large",
        //     muitoGrande: "Very Large",
        //     nenhumaSecaoEncontrada: "No section found",
        //     labelSecaoTi: "IT Section",
        //     nenhumaBuEncontrada: "No BU found",
        //     buSolicitante: "Requesting BU",
        //     labelBusBeneficiadas: "Benefited BUs",
        //     selecioneUmaOuMaisBus: "Select one or more BUs",
        //     nenhumForumEncontrado: "No forum found",
        //     labelForum: "Forum",
        //     anexos: "Attachments",
        //     titleBaixar: "Download",
        //     titleRemover: "Remove",
        //     nenhumAnexoAdicionado: "No attachments added",
        // },
        // Header: {
        //     paginaInicial: "Home",
        // },
        // idiomaModal: {
        //     idiomas: "Languages",
        // },
        // linhaTabelaCcs: {
        //     titleExcluirLinha: "Delete line",
        //     digiteCodigo: "Enter the code...",
        // },
        // linhaTabelaCustos: {
        //     digiteTipo: "Enter the type...",
        //     digitePerfil: "Enter the profile...",
        //     digitePeriodo: "Enter the period...",
        //     digiteHoras: "Enter the hours...",
        //     digiteValor: "Enter the value...",
        //     titleExcluirLinha: "Delete line",
        // },
        // modalAceitarDemanda: {
        //     informacoes: "Information",
        //     tamanho: "Size",
        //     muitoPequeno: "Very Small",
        //     pequeno: "Small",
        //     medio: "Medium",
        //     grande: "Large",
        //     muitoGrande: "Very Large",
        //     buSolicitante: "Requesting BU",
        //     nenhumaBuEncontrada: "No BU found",
        //     busBeneficiadas: "Benefited BUs",
        //     selecioneUmaOuMaisBus: "Select one or more BUs",
        //     nenhumaSecaoEncontrada: "No section found",
        //     secaoTi: "IT Section",
        //     forum: "Forum",
        //     nenhumForumEncontrado: "No forum found",
        //     anexos: "Attachments",
        //     nenhumAnexoAdicionado: "No attachments added",
        //     cancelar: "Cancel",
        //     aceitar: "Accept",
        // },
        // modalConfirmacao: {
        //     mensagensModal: {
        //         descartarRascunho: "Do you want to discard the scope?",
        //         sairCriacao: "Do you want to leave the demand creation?",
        //         enviarDemanda: "Do you want to create the demand?",
        //         sairSemSalvar: "Do you want to leave without saving?",
        //         descartarProposta: "Do you want to discard the proposal?",
        //         cancelarEdicao: "Do you want to discard the changes?",
        //         aceitarDemanda: "Do you want to accept the demand?",
        //         confirmarExclusao: "Are you sure you want to delete?",
        //         fecharChat: "Do you really want to close this chat?",
        //     },
        //     mensagensBotao: {
        //         sim: "Yes",
        //         enviar: "Send",
        //         criar: "Create",
        //         aceitar: "Accept",
        //     },
        //     cancelar: "Cancel",
        // },
        // modalFiltro: {
        //     status: "Status",
        //     labels: {
        //         aprovada: "Approved",
        //         reprovada: "Disapproved",
        //         aguardandoEdicao: "Waiting for Edition",
        //         aguardandoRevisao: "Waiting for Review",
        //         emAprovacao: "In Approval",
        //         emAndamento: "In Progress",
        //     },
        // },
        // modalFiltroGerencia: {
        //     filtros: "Filters",
        //     semResultados: "No results found",
        //     labelSolicitante: "Requester",
        //     forum: "Forum",
        //     selecionar: "Select",
        //     tamanho: "Size",
        //     semResultados: "No results found",
        //     analistaResponsavel: "Responsible Analyst",
        //     gerenteResponsavel: "Responsible Manager",
        //     muitoPequeno: "Very Small",
        //     pequeno: "Small",
        //     medio: "Medium",
        //     grande: "Large",
        //     muitoGrande: "Very Large",
        //     departamento: "Department",
        //     numero: "Number",
        //     limparFilros: "Clear Filters",
        // },
        // modalHistoricoDemanda: {
        //     historico: "History",
        // },
        // modalInformarMotivo: {
        //     informarMotivo: "Inform Reason",
        //     informeMotivo: "Enter the reason...",
        //     confirmar: "Confirm",
        // },
        // modalMotivoRecusa: {
        //     motivoDaRecusa: "Reason for refusal",
        // },
        // modalOrdenacao: {
        //     score: "Score",
        //     maiorScore: "Highest Score",
        //     menorScore: "Lowest Score",
        //     titulo: "Title",
        //     az: "A-Z",
        //     za: "Z-A",
        //     data: "Date",
        //     maisRecente: "Most recent",
        //     maisAntiga: "Oldest",
        // },
        // modalRecusarDemanda: {
        //     motivoDaRecusa: "Reason for refusal",
        //     informeMotivo: "Enter the reason...",
        //     enviar: "Send",
        // },
        // notificacao: {
        //     diasAtras: "days ago",
        //     hoje: "today",
        //     umaSemanaAtras: "1 week ago",
        //     duasSemanasAtras: "2 weeks ago",
        //     tresSemanasAtras: "3 weeks ago",
        //     quatroSemanasAtras: "4 weeks ago",
        //     umMesAtras: "1 month ago",
        // },
        // notificacaoModal: {
        //     notificacaoLidaComSucesso: "Notification read successfully!",
        //     notificacoes: "Notifications",
        //     nenhumaNotificaçaoEncontrada: "No notification found!",
        //     verTudo: "See all",
        //     verNotificacoes: "See notifications",
        // },
        // paginacao: {
        //     itensPorPagina: "Items per page",
        // },
        // pauta: {
        //     deletar: "Delete",
        //     comissao: "Commission",
        //     analistaResponsavel: "Responsible Analyst",
        // },
        // pautaAtaModoVisualizacao: {
        //     as: "to",
        //     numeroSequencial: "Seq. Num.",
        //     comissao: "Commission",
        //     analistaResponsavel: "Respon. Anal.",
        //     deletar: "Delete",
        //     data: "Date",
        //     nadaEncontrados: "Nothing found",
        //     tenteNovamenteMaisTarde: "Try again later",
        // },
        // propostaDeAta: {
        //     codigoPpm: "PPM Code",
        //     tituloDaProposta: "Proposal Title",
        //     responsavelDoNegocio: "Business Responsible",
        //     problema: "Problem",
        //     proposta: "Proposal",
        //     beneficios: "Benefits",
        //     frequenciaDeUso: "Frequency of Use",
        //     custos: "Costs",
        //     custosAqui: "Costs here",
        //     periodoDeExecucao: "Execution Period",
        //     paybackSimples: "Simple Payback",
        //     linkDoJira: "Jira Link",
        //     anexos: "Attachments",
        //     parecerComissao: "Commission Opinion",
        //     maisInformacoes: "More Information",
        //     businessCase: "Business Case",
        //     escrevaNovaInformacao: "Write new information...",
        //     parecerDG: "DG Opinion",
        //     aprovado: "Approved",
        //     reprovado: "Disapproved",
        // },
        // responsavelNegocional: {
        //     responsavelDoNegocio: "Business Responsible",
        //     insiraResponsavelDoNegocio: "Enter the business responsible...",
        //     area: "Area",
        //     insiraAreaDoResponsavel: "Enter the responsible area...",
        // },
        // textEditor: {
        //     digiteAquiEscopoDaProposta: "Enter here the proposal scope...",
        // },
        // userModal: {
        //     normal: "Normal",
        //     pequeno: "Small",
        //     muitoPequeno: "Very Small",
        //     grande: "Large",
        //     muitoGrande: "Very Large",
        //     configuracoes: "Settings",
        //     escopos: "Drafts",
        //     chats: "Chats",
        //     A: "A",
        //     diminuirFonte: "Decrease font",
        //     aumentarFonte: "Increase font",
        //     modoClaroEscuro: "Light/Dark Mode",
        //     sair: "Exit",
        // },
        // chat: {
        //     tour: {
        //         tour1: "In this input you can search for chats by user name and by the sequential number of the demand.",
        //         tour2: "Here are the open chats, having the user name, the sequential number of the demand and from which demand it belongs.",
        //         tour3: "In this button you can choose between minimizing the chat or ending the conversation (closing the chat).",
        //         tour4: "Here you can write what you want to send, you can also attach a file.",
        //     },
        //     pesquisarPorNome: "Search by name...",
        //     usuarioTour: {
        //         tour: "Tour",
        //         gerente: "Manager",
        //         mostrarNoTour: "Show in tour",
        //         olaTudoBem: "Hello, how are you?",
        //         tudoSimVoce: "Fine, and you?",
        //         eu: "Me",
        //         bemTambemObrigado: "Fine, thank you!",
        //     },
        //     usuario: "User",
        //     selecioneAlgumaConversa: "Select some conversation",
        //     miniChatAberto: "Mini chat opened",
        //     opcoes: "Options",
        //     abrirPopUp: "Open pop-up",
        //     encerrarChat: "Close chat",
        //     escrevaSuaMensagem: "Write your message...",
        //     enviarAnexo: "Send attachment",
        //     enviarMensagem: "Send message",
        // },
        // detalhesAta: {
        //     ataCriadaComSucesso: "Minutes created successfully!",
        //     ata: "Minutes",
        //     numeroSequencial: "Seq. Num.",
        //     data: "Date",
        //     inicio: "Start",
        //     fim: "End",
        //     sumario: "Summary",
        //     proposta: "Proposal",
        //     voltar: "Back",
        //     navegacao: "Navigation",
        //     publicarAta: "Publish Minutes",
        //     proximo: "Next",
        //     publicar: "Publish",
        // },
        // detalhesDemandaPagina: {
        //     tour: {
        //         tour1: "This is the demand details page. Here you can see all the details of the selected demand.",
        //         tour2: "By clicking here, you can download this demand in PDF format.",
        //         tour3: "By clicking on this pencil, you can edit this demand.",
        //     }
        // },
        // detalhesPauta: {
        //     baixarPDF: "PDF Download",
        //     pauta: "Minutes",
        //     numeroSequencial: "Seq. Num.",
        //     ano: "Year",
        //     sumario: "Summary",
        //     proposta: "Proposal",
        //     voltar: "Back",
        //     proximo: "Next",
        //     navegacao: "Navigation",
        //     criarAta: "Create Minutes",
        // },
        // escopos: {
        //     tour: {
        //         tour1: "Here is the search bar, where you can search by a title.",
        //         tour2: "Here are the automatically created scopes, in each scope it is possible to open again for editing. A scope is created for each project you open and do not finish.",
        //         tour3: "In this area you can see what percentage of the form is filled in.",
        //         tour4: "By clicking on the trash can you delete the scope.",
        //     },
        //     pesquisarPorTitulo: "Search by title...",
        //     pesquisar: "Search",
        //     escopoDeletadoComSucesso: "Scope deleted successfully!",
        // },
        // home: {
        //     tourAjuda: {
        //         barraDePesquisa: "Here is the search bar, where you can search by a title.",
        //         iconeOredenar: "In this icon you can order your demands by title (A-Z or Z-A), Score (Highest to lowest or lowest to highest) and by date (Newest to oldest or oldest to newest).",
        //         botaoFiltrar: "In this button you can filter your demands by their status.",
        //         modoVisualizacao: "In this part you can change the way you view your demands. You can choose between viewing the demands in the form of a list or in the form of cards.",
        //         criarNovaDemanda: "Here you can start creating a new demand.",
        //         areaDemanda: "In this area you can see your demands. You can click on a demand to see more details.",
        //         statusDemanda: "Here you can see the status of your demand.",
        //         botaoMotivo: "Here you can see the reason why it was rejected or the reason for the edit.",
        //     },
        //     demandaCriadaComSucesso: "Demand created successfully!",
        //     minhasDemandas: "My Demands",
        //     meuDepartamento: "My Department",
        //     visualizacaoEmTabela: "Table View",
        //     visualizacaoEmBloco: "Block View",
        //     pesquisarPorTitulo: "Search by title...",
        //     pesquisar: "Search",
        //     ordenacao: "Order",
        //     filtrar: "Filter",
        //     criarDemanda: "Create Demand",
        //     demandaTour: "Demand Tour",
        //     esseUmExemploDeDemanda: "This is an example of a demand.",
        //     esseUmExemploDeDemanda: "This is an example of a demand",
        //     nomeDoSolicitante: "Requester Name",
        // },
        // homeGerencia: {
        //     toursDemandas: {
        //         tour1: "Here is the search bar, where you can search by a title of a demand.",
        //         tour2: "This is the sorting icon, where you can order the items alphabetically, by score or by creation date.",
        //         tour3: "Here is the filter, where you can filter by: Requester, Responsible Manager, Forum, Department, Size and number.",
        //         tour4: "Here is the place to export the demands in spreadsheet format.",
        //         tour5: "Here you can start the process of creating a new demand.",
        //         tour6: "In this area are the demands, where you can click on a demand to see more details.",
        //         tour7: "By clicking here you can see the demand's history of changes.",
        //         tour8: "In this area you can see the status of the demand.",
        //         tour9: "By clicking here you can change the way you view the demands to table or cards.",
        //     },
        //     toursCriarPropostas: {
        //         tour1: "In this area are the demands, where you can click on a demand to see more details and/or create a proposal.",
        //         tour2: "In this area you can see the demand's status.",
        //         tour3: "By clicking here you can see the demand's history of changes.",
        //     },
        //     toursPropostas: {
        //         tour1: "In this area are the proposals, where you can click on a proposal to see more details.",
        //         tour2: "By clicking here you can open the chat with the demand requester.",
        //         tour3: "By clicking here you can see the proposal's history of changes.",
        //     },
        //     toursPautas: {
        //         tour1: "In this part are the minutes, where you can click on a minute to see more details.",
        //         tour2: "By clicking here you can delete the minute.",
        //     },
        //     toursAtas: {
        //         tour1: "In this part are the minutes, where you can click on a minute to see more details.",
        //     },
        //     feedback: {
        //         feedback1: "Minutes published successfully!",
        //         feedback2: "Demand accepted successfully!",
        //         feedback3: "Demand rejected successfully!",
        //         feedback4: "Demand returned successfully!",
        //         feedback5: "Proposal created successfully!",
        //     },
        //     demandas: "Demands",
        //     criarPropostas: "Create Proposals",
        //     propostas: "Proposals",
        //     pautas: "Agendas",
        //     atas: "Guidelines",
        //     visualizacaoEmTabela: "Table View",
        //     visualizacaoEmBloco: "Block View",
        //     pesquisarPorTitulo: "Search by title...",
        //     pesquisar: "Search",
        //     ordenacao: "Order",
        //     filtrar: "Filter",
        //     exportar: "Export",
        //     criarDemanda: "Create Demand",
        //     demandaParaTour: "Demand Tour",
        // },
        // login: {
        //     email: "Email",
        //     senha: "Password",
        //     esqueciSenha: "Forgot Password",
        //     entrar: "Login",
        //     feedback: {
        //         dadosInvalidos: "Invalid data!",
        //         preenchaTodosOsCampos: "Fill in all fields!",
        //     },
        // },
        // notFound: {
        //     paginaNaoEncontrada: "Page Not Found!",
        //     desculpePaginaNaoEncontrada: "Sorry, the page you requested was not found!",
        //     porfavorVolteParaPaginaPrincipal: "Please, return to the main page.",
        //     voltar: "Back",
        // },
        // notificacao: {
        //     notificacaoMArcadasComoNaoLidasComSucesso: "Notifications marked as unread successfully!",
        //     notificacaoMArcadasComoLidasComSucesso: "Notifications marked as read successfully!",
        //     notificacaoExcluidasComSucesso: "Notifications deleted successfully!",
        //     notificacoes: "Notifications",
        //     deletar: "Delete",
        //     marcarComoLido: "Mark as read",
        //     tipo: "Type",
        //     titulo: "Title",
        //     data: "Date",
        //     marcarComoNaoLido: "Mark as unread",
        //     marcarCommoLido: "Mark as read",
        //     deletar: "Delete",
        //     naoHaNotificacoes: "There are no notifications",
        // },
        // detalhesProposta: {
        //     ppm: "PPM",
        //     solicitante: "Requester",
        //     objetivo: "Objective",
        //     proposta: "Proposal",
        //     problema: "Problem",
        //     escopoDaProposta: "Proposal Scope",
        //     periodoDeExecucao: "Execution Period",
        //     payback: "Payback",
        //     reponsaveisPeloNegocio: "Business Responsible",
        //     ate: "to",
        //     tabelaDeCustos: "Cost Table",
        //     tipoDaDespesa: "Expense Type",
        //     perfilDaDespesa: "Expense Profile",
        //     periodoDeExecucaoTabela: "Execution Period (months)",
        //     horas: "Hours",
        //     valorHora: "Hour Value",
        //     total: "Total",
        //     ccs: "CCs",
        //     porcentagem: "Percentage",
        //     anexos: "Attachments",
        //     download: "Download",
        //     semAnexos: "Proposal without attachments",
        //     beneficios: "Benefits",
        //     semBeneficios: "Proposal without benefits",
        //     tipoBeneficio: "Type",
        //     valorMensal: "Monthly Value",
        //     moeda: "Currency",
        //     memoriaCalculo: "Calculation Memory",
        //     busBeneficiadas: "Benefited BUs",
        //     semBuBeneficiada: "Proposal without benefited BUs",
        //     buSolicitante: "Requester BU",
        //     frequencia: "Frequency",
        //     linkJira: "Jira Link",
        //     tamanho: "Size",
        //     data: "DATE",
        //     gerente: "Manager",
        //     pareceres: "Opinions",
        //     forum: "Forum",
        //     aprovado: "Approved",
        //     reprovado: "Disapproved",
        //     devolvido: "Returned",
        //     businessCase: "Business Case",
        //     parecer: "Opinion",
        // },
        // modalAddPropostaPauta: {
        //     selecioneAPauta: "Select a minute",
        //     propostas: "Proposals",
        //     comissao: "Commission",
        //     adicionarComoProposta: "Add as proposal",
        //     publicada: "Published",
        //     naoPublicada: "Not published",
        //     novaPauta: "New Minute",
        //     adicionar: "Add",
        //     numSequencial: "Seq. Number",
        //     essaPropostaJaSeEncontraEmUmaPauta: "This proposal is already in a minute!",
        // }

    } : null;
}

export default TextLanguage;