const TextLanguage = (linguagem) => {
    return linguagem == "pt" ? {
        linguagem: "pt",
        barraProgressaoDemanda: {
            erroPularPasso: "Você não pode pular um passo que não é opcional!",
            botaoVoltar: "Voltar",
            botaoPular: "Pular",
            botaoCriar: "Criar",
            botaoProximo: "Próximo",
            mensagemFeedback: "Preencha todos os campos obrigatórios!"
        },
        barraProgressaoProposta: {
            botaoVoltar: "Voltar",
            botaoCriar: "Criar",
            botaoProximo: "Próximo",
        },
        beneficios: {
            beneficios: "Benefícios",
            real: "Real",
            potencial: "Potencial",
            qualitativo: "Qualitativo",
            valorMensal: "Valor Mensal",
            moeda: "Moeda",
            tiposDeMoeda: {
                real: "BRL",
                dolar: "USD",
                euro: "EUR",
            },
            memoriaCalcula: "Memória de cálculo",
            digiteMemoriaCalculo: "Digite a memória de cálculo...",
        },
        BeneficiosDetalheDemanda: {
            tipo: "Tipo",
            valorMensal: "Valor Mensal",
            moeda: "Moeda",
            memoriaCalculo: "Memória de Cálculo",
            real: "Real",
            potencial: "Potencial",
            qualitativo: "Qualitativo",
            digiteValorPensal: "Digite o valor mensal...",
            tiposDeMoeda: {
                real: "BRL",
                dolar: "USD",
                euro: "EUR",
            },
            digiteMemoriaCalculo: "Digite a memória de cálculo...",
        },
        caminho: {
            home: "Home",
        },
        chatMinimizado: {
            minimizar: "Minimizar",
            maximazar: "Maximizar",
            telaCheia: "Tela Cheia",
            fecharChat: "Fechar Chat",
            escrevaSuaMensagem: "Escreva sua mensagem...",
            enviarAnexo: "Enviar Anexo",
            enviarMensagem: "Enviar Mensagem",
        },
        containerPauta: {
            propostas: "Propostas",
        },
        contato: {
            demanda: "Demanda",
        },
        custos: {
            excluirTabelaDeCustos: "Excluir tabela de custos",
            tipoDaDespesa: "Tipo da Despesa",
            perfilDaDespesa: "Perfil da Despesa",
            periodoDeExecucao: "Período de Execução (Meses)",
            horas: "Horas",
            valorHora: "Valor Hora",
            total: "Total",
            moeda: "R$",
            ccs: "CCs",
        },
        demanda: {
            status: {
                reprovada: "Reprovada",
                aguardandoRevisao: "Aguardando Revisão",
                aguardandoEdicao: "Aguardando Edição",
                emAprovacao: "Em Aprovação",
                aprovada: "Aprovada",
                emAndamento: "Em Andamento",
            },
            motivo: "Motivo",
        },
        demandaGerencia: {
            backlog: "Backlog",
            assessment: "Assessment",
            ppm: "PPM",
            solicitante: "Solicitante",
            departamento: "Departamento",
            gerenteResponsavel: "Gerente Responsável",
        },
        demandaGerenciaModoVisualização: {
            backlog: "Backlog",
            assessment: "Assessment",
            titulo: "Título",
            solicitante: "Solicitante",
            departamento: "Departamento",
            gerenteResponsavel: "Gerente Responsável",
            status: "Status",
            data: "Data",
            naoAtribuido: "Não atribuído",
            historico: "Histórico",
            chat: "Chat",
            nadaEncontrado: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        demandaModoVisualizacao: {
            status: {
                reprovada: "Reprovada",
                aguardandoRevisao: "Aguardando Revisão",
                aguardandoEdicao: "Aguardando Edição",
                emAprovacao: "Em Aprovação",
                aprovada: "Aprovada",
            },
            codigo: "Código",
            titulo: "Titulo",
            status: "Status",
            data: "Data",
            motivo: "Motivo",
            nadaEncontrado: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        DetalhesDemanda: {
            facaAlgumaAlteracaoParaPoderSalvar: "Faça alguma alteração para poder salvar!",
            jaHaUmAnexoComEsseNome: "Já há um anexo com esse nome!",
            problema: "Problema",
            proposta: "Proposta",
            beneficios: "Benefícios",
            frequenciaDeUso: "Frequência de Uso",
            tamanho: "Tamanho",
            secaoDeTi: "Seção de TI",
            buSolicitante: "BU Solicitante",
            busBeneficiadas: "BUs Beneficiadas",
            forum: "Fórum",
            anexos: "Anexos",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
            digiteTituloDaDemanda: "Digite o título da demanda...",
            digiteProblema: "Digite o problema...",
            digiteProposta: "Digite a proposta...",
            baixar: "Baixar",
            remover: "Remover",
            botaoRecusar: "Recusar",
            botaoDevolver: "Devolver",
            botaoAceitar: "Aceitar",
            botaoSalvar: "Salvar",
        },
        escopo: {
            titleExcluir: "Excluir",
        },
        formularioAnexosDemanda: {
            arrasteSolteParaAdicionarUmArquivo: "Arraste & Solte para Adicionar um Arquivo",
            solteParaAdicionarArquivo: "Solte para Adicionar um Arquivo",
            ou: "OU",
            pesquisarArquivos: "Pesquisar Arquivos",
            nome: "Nome",
            tipo: "Tipo",
            remover: "Remover",
        },
        formularioBeneficiosDemanda: {
            adicionar: "Adicionar",
        },
        formularioCustosProposta: {
            total: "Total",
            moeda: "R$",
            adicionarCustos: "Adicionar Custos",
        },
        formularioDadosDemanda: {
            titulo: "Título",
            digiteTitulo: "Digite o título...",
            problema: "Problema",
            digiteProblema: "Digite o problema...",
            proposta: "Proposta",
            digiteProposta: "Digite a proposta...",
            frequenciaDeUso: "Frequencia de uso",
            digiteFrequenciaDeUso: "Digite a frequencia de uso...",
        },
        formularioGeralProposta: {
            periodoDeExecucao: "Período de execução",
            digiteCodigo: "Digite o código...",
            paybackSimples: "Payback simples",
            quantidade: "Qtd",
            dias: "Dias",
            semanas: "Semanas",
            meses: "Meses",
            codigoPpm: "Código PPM",
            linkDoJira: "Link do Jira",
            insiraLinkDoJira: "Insira o link do Jira...",
            responsavelResponsaveis: "Responsável/Responsáveis",
            titleAdicionarNovoResponsavel: "Adicionar um novo responsável",
            anexos: "Anexos",
            adicionarNovoAnexo: "Adicionar um novo anexo",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
        },
        formularioPropostaProposta: {
            digiteTituloDaDemanda: "Digite o título da demanda...",
            problema: "Problema",
            digiteProblema: "Digite o problema...",
            proposta: "Proposta",
            digiteProposta: "Digite a proposta...",
            beneficios: "Beneficios",
            frequenciaDeUso: "Frequência de uso",
            digiteFrequencia: "Digite a frequência...",
            labelTamanho: "Tamanho",
            nenhumaSecaoEncontrada: "Nenhuma seção encontrada",
            labelSecaoTi: "Seção TI",
            nenhumaBuEncontrada: "Nenhuma BU encontrada",
            buSolicitante: "BU Solicitante",
            labelBusBeneficiadas: "BUs Beneficiadas",
            selecioneUmaOuMaisBus: "Selecione uma ou mais BUs",
            nenhumForumEncontrado: "Nenhum fórum encontrado",
            labelForum: "Fórum",
            anexos: "Anexos",
            titleBaixar: "Baixar",
            titleRemover: "Remover",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
        },
        Header: {
            paginaInicial: "Página Inicial",
        },
        idiomaModal: {
            idiomas: "Idiomas",
        },
        linhaTabelaCcs: {
            titleExcluirLinha: "Excluir linha",
            digiteCodigo: "Digite o código...",
        },
        linhaTabelaCustos: {
            tipo: "Tipo",
            tipo1: "Tipo 1",
            tipo2: "Tipo 2",
            tipo3: "Tipo 3",
            perfil: "Perfil",
            perfil1: "Perfil 1",
            perfil2: "Perfil 2",
            perfil3: "Perfil 3",
            digitePeriodo: "Digite o período...",
            digiteHoras: "Digite as horas...",
            digiteValor: "Digite o valor...",
            titleExcluirLinha: "Excluir linha",
            secaoTi1: "Seção TI 1",
            secaoTi2: "Seção TI 2",
            secaoTi3: "Seção TI 3",
            informacoes: "Informações",
            labelTamanho: "Tamanho",
            labelBuSolicitante: "BU Solicitante",
            nenhumaBuEncontrada: "Nenhuma BU encontrada",
            busBeneficiadas: "BUs Beneficiadas",
            selecioneUmaOuMaisBus: "Selecione Uma Ou Mais Bus",
            nenhumaSecaoEncontrada: "Nenhuma seção encontrada",
            labelSecaoTi: "Seção TI",
            label: "Fórum",
            nenhumForumEncontrado: "Nenhum fórum encontrado",
            anexos: "Anexos",
            nenhumAnexoAdicionado: "Nenhum anexo adicionado",
            cancelar: "Cancelar",
            aceitar: "Aceitar",
            selecionePauta: "Selecione a Pauta",
            propostas: "Propostas",
            comissao: "Comissão",
            exemplo1: "Exemplo 1",
            exemplo2: "Exemplo 2",
            propostas: "Propostas",
            adicionarComoProposta: "Adicionar Como Proposta",
            labelPublicada: "Publicada",
            labelNaoPublicada: "Não Publicada",
            butaoCriarPauta: "Criar Pauta",
            botaoAdicionar: "Adicionar",
        },
        modalConfirmacao: {
            mensagensModal: {
                descartarRascunho: "Deseja descartar o escopo?",
                sairCriacao: "Deseja sair da criação da demanda?",
                enviarDemanda: "Deseja criar a demanda?",
                sairSemSalvar: "Deseja sair sem salvar?",
                descartarProposta: "Deseja descartar a proposta?",
                cancelarEdicao: "Deseja descartar as alterações?",
                aceitarDemanda: "Deseja aceitar a demanda?",
                confirmarExclusao: "Tem certeza que deseja excluir?",
                fecharChat: "Deseja realmente fechar este chat?",
            },
            mensagensBotao: {
                sim: "Sim",
                enviar: "Enviar",
                criar: "Criar",
                aceitar: "Aceitar",
            },
            cancelar: "Cancelar",
        },
        modalFiltro: {
            status: "Status",
            labels: {
                aprovada: "Aprovada",
                reprovada: "Reprovada",
                aguardandoEdicao: "Aguardando Edição",
                aguardandoRevisao: "Aguardando Revisão",
                emAprovacao: "Em Aprovação",
                emAndamento: "Em Andamento",
            },
        },
        modalFiltroGerencia: {
            filtros: "Filtros",
            labelSolicitante: "Solicitante",
            forum: "Fórum",
            selecionar: "Selecionar",
            tamanho: "Tamanho",
            selecionar: "Selecionar",
            muitoPequeno: "Muito Pequeno",
            pequeno: "Pequeno",
            medio: "Médio",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            departamento: "Departamento",
            numero: "Número",
            limparFilros: "Limpar Filtros",
        },
        modalHistoricoDemanda: {
            historico: "Histórico",
        },
        modalInformarMotivo: {
            informarMotivo: "Informar Motivo",
            informeMotivo: "Informe o motivo...",
            confirmar: "Confirmar",
        },
        modalMotivoRecusa: {
            motivoDaRecusa: "Motivo da recusa",
        },
        modalOrdenacao: {
            score: "Score",
            maiorScore: "Maior Score",
            menorScore: "Menor Score",
            titulo: "Título",
            az: "A-Z",
            za: "Z-A",
            data: "Data",
            maisRecente: "Mais recente",
            maisAntiga: "Mais antiga",
        },
        modalRecusarDemanda: {
            motivoDaRecusa: "Motivo da recusa",
            informeMotivo: "Informe o motivo...",
            enviar: "Enviar",
        },
        notificacao: {
            diasAtras: "dias atrás",
            hoje: "hoje",
            umaSemanaAtras: "1 semana atrás",
            duasSemanasAtras: "2 semanas atrás",
            tresSemanasAtras: "3 semanas atrás",
            quatroSemanasAtras: "4 semanas atrás",
            umMesAtras: "1 mês atrás",
        },
        notificacaoModal: {
            notificacaoLidaComSucesso: "Notificação lida com sucesso!",
            notificacoes: "Notificações",
            nenhumaNotificaçaoEncontrada: "Nenhuma notificação encontrada!",
            verTudo: "Ver tudo",
            verNotificacoes: "Ver notificações",
        },
        paginacao: {
            itensPorPagina: "Itens por página",
            20: "20",
            40: "40",
            60: "60",
            80: "80",
        },
        pauta: {
            comissao: "Comissão",
            analistaResponsavel: "Analista Responsável",
        },
        pautaAtaModoVisualizacao: {
            numeroSequencial: "Num. Seq.",
            comissao: "Comissão",
            analistaResponsavel: "Anal. Resp.",
            data: "Data",
            nadaEncontrados: "Nada encontrado",
            tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        },
        propostaDeAta: {
            codigoPpm: "Código PPM",
            tituloDaProposta: "Título da Proposta",
            responsavelDoNegocio: "Responsável do Negócio",
            problema: "Problema",
            proposta: "Proposta",
            beneficios: "Benefícios",
            frequenciaDeUso: "Frequência de Uso",
            custos: "Custos",
            custosAqui: "Custos aqui",
            periodoDeExecucao: "Período de Execução",
            paybackSimples: "Payback Simples",
            linkDoJira: "Link Do Jira",
            anexos: "Anexos",
            parecerComissao: "Parecer Comissão",
            aprovado: "Aprovado",
            reprovado: "Reprovado",
            maisInformacoes: "Mais Informações",
            businessCase: "Business Case",
            aprovado: "Aprovado",
            escrevaNovaInformacao: "Escreva a nova informação...",
            parecerDG: "Parecer DG",
            aprovado: "Aprovado",
            reprovado: "Reprovado",
        },
        responsavelNegocio: {
            responsavelDoNegocio: "Responsável do negócio",
            insiraResponsavelDoNegocio: "Insira o responsável pelo negócio...",
            area: "Área",
            insiraAreaDoResponsavel: "Insira a área do responsável...",
        },
        userModal: {
            normal: "Normal",
            pequeno: "Pequeno",
            muitoPequeno: "Muito Pequeno",
            grande: "Grande",
            muitoGrande: "Muito Grande",
            configuracoes: "Configurações",
            escopos: "Escopos",
            chats: "Chats",
            A: "A",
            modoClaroEscuro: "Modo Claro/Escuro",
            sair: "Sair",
        },
        chat: {
            pesquisarPorNome: "Pesquisar por nome...",
            usuario: "Usuário",
            selecioneAlgumaConversa: "Selecione alguma conversa",
            encerrarChat: "Encerrar chat",
            escrevaSuaMensagem: "Escreva sua mensagem...",
            enviarAnexo: "Enviar anexo",
            enviarMensagem: "Enviar mensagem",
        },
        detalhesAta: {
            ataCriadaComSucesso: "Ata criada com sucesso!",
            ata: "Ata",
            numeroSequencial: "Número Sequencial",
            data: "Data",
            inicio: "Início",
            fim: "Fim",
            sumario: "Sumário",
            proposta: "Proposta",
            voltar: "Voltar",
            proximo: "Próximo",
            publicar: "Publicar",
        },
        detalhesDemandaPagina: {
            tour: {
                tour1: "Essa é a página de detalhes da demanda. Aqui você pode ver todos os detalhes da demanda selecionada.",
                tour2: "Cicando aqui, você consegue baixar em PDF essa demanda.",
                tur3: "Clicando neste lápis, você consegue estar editando as informações.",
            }
        },
        detalhesPauta: {
            pauta: "Pauta",
            numeroSequencial: "Número Sequencial",
            ano: "Ano",
            sumario: "Sumário",
            proposta: "Proposta",
            voltar: "Voltar",
            proximo: "Próximo",
            criarAta: "Criar Ata",
        },
        escopos: {
            tour: {
                tour1: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
                tour2: "Aqui fica os escopos criados automaticamente, em cada escopo é possível abrir novamente para edição. É criado um escopo para cada projeto que você abre e não finaliza.",
                tour3: "Nesta área você consegue visualizar qual a porcentagem preenchida do formulário.",
                tour4: "Clicando na lixeira você exclui o escopo.",
            },
            pesquisarPorTitulo: "Pesquisar por título...",
            pesquisar: "Pesquisar",
            escopoDeletadoComSucesso: "Escopo deletado com sucesso!",
        },
        home: {
            tourAjuda: {
                barraDePesquisa: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
                iconeOredenar: "Neste ícone você pode ordenar as suas demandas por título (A-Z ou Z-A), Score (Maior ao menor ou Menor ao maior) e pela data (Mais nova à mais velha ou Mais velha à Mais nova).",
                botaoFiltrar: "Neste botão você pode filtrar suas demandas por seus status.",
                modoVisualizacao: "Nesta parte você pode trocar o modo de visualização das suas demandas. Você pode escolher entre visualizar as demandas em forma de lista ou em forma de cards.",
                criarNovaDemanda: "Aqui você consegue iniciar a criação de uma nova demanda.",
                areaDemanda: "Nesta área você consegue observar suas demandas. Você pode clicar em uma demanda para ver mais detalhes.",
                statusDemanda: "Nesta área você consegue visualizar o status atual da demanda.",
                botaoMotivo: "Aqui consegue observar o motivo pelo qual foi recusado ou o motivo da edição.",
            },
            demandaCriadaComSucesso: "Demanda criada com sucesso!",
            minhasDemandas: "Minhas Demandas",
            meuDepartamento: "Meu Departamento",
            visualizacaoEmTabela: "Visualização em Tabela",
            visualizacaoEmBloco: "Visualização em Bloco",
            pesquisarPorTitulo: "Pesquisar por título...",
            pesquisar: "Pesquisar",
            ordenacao: "Ordenação",
            filtrar: "Filtrar",
            criarDemanda: "Criar Demanda",
            demandaTour: "Demanda Tour",
            esseUmExemploDeDemanda: "Esse é um exemplo de demanda",
            nomeDoSolicitante: "Nome do Solicitante",
        },
        homeGerencia: {
            toursDemandas: {
                tour1: "Aqui é a barra de pesquisa, você pode pesquisar por algum título de alguma demanda",
                tour2: "Esse é icone de ordenação, onde poderá ordenar os itens por ordem alfabética, por score ou por data de criação",
                tour3: "Aqui fica o filtro, podendo filtrar por: Solicitante, Gerente Responsável, Fórum, Departamento, Tamanho e número",
                tour4: "Aqui fica o lugar para exportar as demandas em formato de planilha",
                tour5: "Aqui pode iniciar o processo de criação de uma nova demanda",
                tour6: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes",
                tour7: "Clicando aqui você pode ver o histórico de alterações da demanda",
                tour8: "Nesta área você pode visualizar o status da demanda",
                tour9: "Clicando aqui você pode alterar o modo de visualização para tabela ou cards",
            },
            toursCriarPropostas: {
                tour1: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes e/ou criar uma proposta",
                tour2: "Nesta área você pode visualizar o status da demanda",
                tour3: "Clique aqui para ver o histórico de alterações da demanda",
            },
            toursPropostas: {
                tour1: "Nesta parte fica as propostas, podendo clicar em uma proposta para ver mais detalhes.",
                tour2: "Clicando aqui você pode abrir o chat com o solicitante da demanda",
                tour3: "Clicando aqui você pode ver o histórico de alterações da proposta",
            },
            toursPautas: {
                tour1: "Nesta parte fica as pautas, podendo clicar em uma pauta para ver mais detalhes.",
                tour2: "Clicando aqui você pode excluir a pauta",
            },
            toursAtas: {
                tour1: "Nesta parte fica as atas, podendo clicar em uma ata para ver mais detalhes",
            },
            feedback: {
                feedback1: "Ata publicada com sucesso!",
                feedback2: "Demanda aceita com sucesso!",
                feedback3: "Demanda recusada com sucesso!",
                feedback4: "Demanda devolvida com sucesso!",
                feedback5: "Proposta criada com sucesso!",
            },
            demandas: "Demandas",
            criarPropostas: "Criar Propostas",
            propostas: "Propostas",
            pautas: "Pautas",
            atas: "Atas",
            visualizacaoEmTabela: "Visualização em tabela",
            visualizacaoEmBloco: "Visualização em bloco",
            pesquisarPorTitulo: "Pesquisar por título...",
            filtrar: "Filtrar",
            exportar: "Exportar",
            criarDemanda: "Criar Demanda",
            demandaParaTour: "Demanda para Tour",
        },
        login: {
            email: "Email",
            senha: "Senha",
            esqueciSenha: "Esqueci a senha",
            entrar: "Entrar",
            feedback: {
                dadosInvalidos: "Dados inválidos!",
                preenchaTodosOsCampos: "Preencha todos os campos!",
            },
        },
        notFound: {
            pageNotFound: "Page Not Found",
            desculpePaginaNaoEncontrada: "Desculpe, a página informada não foi encontrada!",
            porfavorVolteParaPaginaPrincipal: "Por favor, volte para a página principal.",
            voltar: "Voltar",
        },
        notificacao: {
            notificacaoMArcadasComoNaoLidasComSucesso: "Notificações marcadas como não lidas com sucesso!",
            notificacaoMArcadasComoLidasComSucesso: "Notificações marcadas como lidas com sucesso!",
            notificacaoExcluidasComSucesso: "Notificações excluídas com sucesso!",
            notificacoes: "Notificações",
            deletar: "Deletar",
            marcarComoLido: "Marcar como lido",
            tipo: "Tipo",
            titulo: "Titulo",
            data: "Data",
            marcarComoNaoLido: "Marcar como não lido",
            marcarCommoLido: "Marcar como lido",
            deletar: "Deletar",
            naoHaNotificacoes: "Não há notificações",
        },












        detalhesProposta: {
            ppm: "PPM",
            solicitante: "Solicitante",
            objetivo: "Objetivo",
            proposta: "Proposta",
            problema: "Problema",
            escopoDaProposta: "Escopo da Proposta",
            periodoDeExecucao: "Período de Execução",
            payback: "Payback",
            reponsaveisPeloNegocio: "Responsáveis pelo Negócio",
            ate: "até",
            tabelaDeCustos: "Tabela de Custos",
            tipoDaDespesa: "Tipo da Despesa",
            perfilDaDespesa: "Perfil da Despesa",
            periodoDeExecucaoTabela: "Período de Execução (meses)",
            horas: "Horas",
            valorHora: "Valor Hora",
            total: "Total",
            ccs: "CCs",
            porcentagem: "Porcentagem",
            anexos: "Anexos",
            download: "Baixar",
            semAnexos: "Proposta sem anexos",
            beneficios: "Benefícios",
            semBeneficios: "Proposta sem benefícios",
            tipoBeneficio: "Tipo",
            valorMensal: "Valor Mensal",
            moeda: "Moeda",
            memoriaCalculo: "Memória de Cálculo",
            busBeneficiadas: "BUs Beneficiadas",
            semBuBeneficiada: "Proposta sem BUs beneficiadas",
            buSolicitante: "BU Solicitante",
            frequencia: "Frequência",
            linkJira: "Link Jira",
            tamanho: "Tamanho",
            data: "DATA",
            gerente: "Gerente",
            pareceres: "Pareceres",
            forum: "Fórum",
        }
    } : linguagem == "en" ? {
        linguagem: "en",
        barraProgressaoDemanda: {
            erroPularPasso: "You cannot skip a step that is not optional!",
            botaoVoltar: "Back",
            botaoPular: "Skip",
            BotaoCriar: "Create",
            botaoProximo: "Next",
            mensagemFeedback: "You must fill in all the fields!",
        },
        barraProgressaoProposta: {
            botaoVoltar: "Back",
            botaoCriar: "Create",
            botaoProximo: "Next",
        },
        beneficios: {
            beneficios: "Benefits",
            real: "Real",
            potencial: "Potential",
            qualitativo: "Qualitative",
            valorMensal: "Monthly Value",
            moeda: "Currency",
            tiposDeMoeda: {
                real: "BRL",
                dolar: "USD",
                euro: "EUR",
            },
            memoriaCalcula: "Calculation memory",
            digiteMemoriaCalculo: "Enter the calculation memory...",
        },
        BeneficiosDetalheDemanda: {
            tipo: "Type",
            valorMensal: "Monthly Value",
            moeda: "Currency",
            memoriaCalculo: "Calculation memory",
            real: "Real",
            potencial: "Potential",
            qualitativo: "Qualitative",
            digiteValorPensal: "Enter the monthly value...",
            tiposDeMoeda: {
                real: "BRL",
                dolar: "USD",
                euro: "EUR",
            },
            digiteMemoriaCalculo: "Enter the calculation memory...",
        },
        caminho: {
            home: "Home",
        },
        chatMinimizado: {
            minimizar: "Minimize",
            maximazar: "Maximize",
            telaCheia: "Full screen",
            fecharChat: "Close Chat",
            escrevaSuaMensagem: "Write your message...",
            enviarAnexo: "Send Attachment",
            enviarMensagem: "Send Message",
        },
        containerPauta: {
            propostas: "Proposals",
        },
        contato: {
            demanda: "Demand",
        },
        custos: {
            excluirTabelaDeCustos: "Delete cost table",
            tipoDaDespesa: "Expense Type",
            perfilDaDespesa: "Expense Profile",
            periodoDeExecucao: "Execution Period (Months)",
            horas: "Hours",
            valorHora: "Hour Value",
            total: "Total",
            moeda: "R$",
            ccs: "CCs",
        },
        demanda: {
            status: {
                reprovada: "Rejected",
                aguardandoRevisao: "Awaiting Review",
                aguardandoEdicao: "Awaiting Edition",
                emAprovacao: "In Approval",
                aprovada: "Approved",
                emAndamento: "In Progress",
            },
            motivo: "Reason",
        },
        demandaGerencia: {
            backlog: "Backlog",
            assessment: "Assessment",
            ppm: "PPM",
            solicitante: "Requester",
            departamento: "Department",
            gerenteResponsavel: "Responsible Manager",
        },
        demandaGerenciaModoVisualização: {
            backlog: "Backlog",
            assessment: "Assessment",
            titulo: "Title",
            solicitante: "Requester",
            departamento: "Department",
            gerenteResponsavel: "Responsible Manager",
            status: "Status",
            data: "Date",
            naoAtribuido: "Not assigned",
            historico: "History",
            chat: "Chat",
            nadaEncontrado: "Nothing found",
            tenteNovamenteMaisTarde: "Try again later",
        },
        demandaModoVisualizacao: {
            status: {
                reprovada: "Rejected",
                aguardandoRevisao: "Awaiting Review",
                aguardandoEdicao: "Awaiting Edition",
                emAprovacao: "In Approval",
                aprovada: "Approved",
            },
            codigo: "Code",
            titulo: "Title",
            status: "Status",
            data: "Date",
            motivo: "Reason",
            nadaEncontrado: "Nothing found",
            tenteNovamenteMaisTarde: "Try again later",
        },
        DetalhesDemanda: {
            facaAlgumaAlteracaoParaPoderSalvar: "Make some changes to be able to save!",
            jaHaUmAnexoComEsseNome: "There is already an attachment with that name!",
            problema: "Problem",
            proposta: "Proposal",
            beneficios: "Benefits",
            frequenciaDeUso: "Frequency of Use",
            tamanho: "Size",
            secaoDeTi: "IT Section",
            buSolicitante: "Requesting BU",
            busBeneficiadas: "Benefited BUs",
            forum: "Forum",
            anexos: "Attachments",
            nenhumAnexoAdicionado: "No attachments added",
            digiteTituloDaDemanda: "Enter the title of the demand...",
            digiteProblema: "Enter the problem...",
            digiteProposta: "Enter the proposal...",
            baixar: "Download",
            remover: "Remove",
            botaoRecusar: "Reject",
            botaoDevolver: "Return",
            botaoAceitar: "Accept",
            botaoSalvar: "Save",
        },
        escopo: {
            titleExcluir: "Delete",
        },
        formularioAnexosDemanda: {
            arrasteSolteParaAdicionarUmArquivo: "Drag & Drop to Add a File",
            solteParaAdicionarArquivo: "Drop to Add a File",
            ou: "OR",
            pesquisarArquivos: "Search Files",
            nome: "Name",
            tipo: "Type",
            remover: "Remove",
        },
        formularioBeneficiosDemanda: {
            adicionar: "Add",
        },
        formularioCustosProposta: {
            total: "Total",
            moeda: "$",
            adicionarCustos: "Add Costs",
        },
        formularioDadosDemanda: {
            titulo: "Title",
            digiteTitulo: "Enter the title...",
            problema: "Problem",
            digiteProblema: "Enter the problem...",
            proposta: "Proposal",
            digiteProposta: "Enter the proposal...",
            frequenciaDeUso: "Frequency of Use",
            digiteFrequenciaDeUso: "Enter the frequency of use...",
        },
        formularioGeralProposta: {
            periodoDeExecucao: "Execution Period",
            digiteCodigo: "Enter the code...",
            paybackSimples: "Simple Payback",
            quantidade: "Qty",
            dias: "Days",
            semanas: "Weeks",
            meses: "Months",
            codigoPpm: "PPM Code",
            linkDoJira: "Jira Link",
            insiraLinkDoJira: "Enter the Jira link...",
            responsavelResponsaveis: "Responsible/Responsibles",
            titleAdicionarNovoResponsavel: "Add a new responsible",
            anexos: "Attachments",
            adicionarNovoAnexo: "Add a new attachment",
            nenhumAnexoAdicionado: "No attachments added",
        },
        formularioPropostaProposta: {
            digiteTituloDaDemanda: "Enter the title of the demand...",
            problema: "Problem",
            digiteProblema: "Enter the problem...",
            proposta: "Proposal",
            digiteProposta: "Enter the proposal...",
            beneficios: "Benefits",
            frequenciaDeUso: "Frequency of Use",
            digiteFrequencia: "Enter the frequency...",
            labelTamanho: "Size",
            nenhumaSecaoEncontrada: "No section found",
            labelSecaoTi: "IT Section",
            nenhumaBuEncontrada: "No BU found",
            buSolicitante: "Requesting BU",
            labelBusBeneficiadas: "Benefited BUs",
            selecioneUmaOuMaisBus: "Select one or more BUs",
            nenhumForumEncontrado: "No forum found",
            labelForum: "Forum",
            anexos: "Attachments",
            titleBaixar: "Download",
            titleRemover: "Remove",
            nenhumAnexoAdicionado: "No attachments added",
        },
        Header: {
            paginaInicial: "Home",
        },
        idiomaModal: {
            idiomas: "Languages",
        },
        linhaTabelaCcs: {
            titleExcluirLinha: "Delete line",
            digiteCodigo: "Enter the code...",
        },
        linhaTabelaCustos: {
            tipo: "Type",
            tipo1: "Type 1",
            tipo2: "Type 2",
            tipo3: "Type 3",
            perfil: "Profile",
            perfil1: "Profile 1",
            perfil2: "Profile 2",
            perfil3: "Profile 3",
            digitePeriodo: "Enter the period...",
            digiteHoras: "Enter the hours...",
            digiteValor: "Enter the value...",
            titleExcluirLinha: "Delete line",
            secaoTi1: "IT Section 1",
            secaoTi2: "IT Section 2",
            secaoTi3: "IT Section 3",
            informacoes: "Information",
            labelTamanho: "Size",
            labelBuSolicitante: "Requesting BU",
            nenhumaBuEncontrada: "No BU found",
            busBeneficiadas: "Benefited BUs",
            selecioneUmaOuMaisBus: "Select one or more BUs",
            nenhumaSecaoEncontrada: "No section found",
            labelSecaoTi: "IT Section",
            label: "Forum",
            nenhumForumEncontrado: "No forum found",
            anexos: "Attachments",
            nenhumAnexoAdicionado: "No attachments added",
            cancelar: "Cancel",
            aceitar: "Accept",
            selecionePauta: "Select a topic",
            propostas: "Proposals",
            comissao: "Commission",
            exemplo1: "Example 1",
            exemplo2: "Example 2",
            propostas: "Proposals",
            adicionarComoProposta: "Add as a Proposal",
            labelPublicada: "Published",
            labelNaoPublicada: "Not Published",
            butaoCriarPauta: "Create Topic",
            botaoAdicionar: "Add",
        },

    
        // modalConfirmacao: {
        //     mensagensModal: {
        //         descartarRascunho: "Deseja descartar o escopo?",
        //         sairCriacao: "Deseja sair da criação da demanda?",
        //         enviarDemanda: "Deseja criar a demanda?",
        //         sairSemSalvar: "Deseja sair sem salvar?",
        //         descartarProposta: "Deseja descartar a proposta?",
        //         cancelarEdicao: "Deseja descartar as alterações?",
        //         aceitarDemanda: "Deseja aceitar a demanda?",
        //         confirmarExclusao: "Tem certeza que deseja excluir?",
        //         fecharChat: "Deseja realmente fechar este chat?",
        //     },
        //     mensagensBotao: {
        //         sim: "Sim",
        //         enviar: "Enviar",
        //         criar: "Criar",
        //         aceitar: "Aceitar",
        //     },
        //     cancelar: "Cancelar",
        // },
        // modalFiltro: {
        //     status: "Status",
        //     labels: {
        //         aprovada: "Aprovada",
        //         reprovada: "Reprovada",
        //         aguardandoEdicao: "Aguardando Edição",
        //         aguardandoRevisao: "Aguardando Revisão",
        //         emAprovacao: "Em Aprovação",
        //         emAndamento: "Em Andamento",
        //     },
        // },
        // modalFiltroGerencia: {
        //     filtros: "Filtros",
        //     labelSolicitante: "Solicitante",
        //     forum: "Fórum",
        //     selecionar: "Selecionar",
        //     tamanho: "Tamanho",
        //     selecionar: "Selecionar",
        //     muitoPequeno: "Muito Pequeno",
        //     pequeno: "Pequeno",
        //     medio: "Médio",
        //     grande: "Grande",
        //     muitoGrande: "Muito Grande",
        //     departamento: "Departamento",
        //     numero: "Número",
        //     limparFilros: "Limpar Filtros",
        // },
        // modalHistoricoDemanda: {
        //     historico: "Histórico",
        // },
        // modalInformarMotivo: {
        //     informarMotivo: "Informar Motivo",
        //     informeMotivo: "Informe o motivo...",
        //     confirmar: "Confirmar",
        // },
        // modalMotivoRecusa: {
        //     motivoDaRecusa: "Motivo da recusa",
        // },
        // modalOrdenacao: {
        //     score: "Score",
        //     maiorScore: "Maior Score",
        //     menorScore: "Menor Score",
        //     titulo: "Título",
        //     az: "A-Z",
        //     za: "Z-A",
        //     data: "Data",
        //     maisRecente: "Mais recente",
        //     maisAntiga: "Mais antiga",
        // },
        // modalRecusarDemanda: {
        //     motivoDaRecusa: "Motivo da recusa",
        //     informeMotivo: "Informe o motivo...",
        //     enviar: "Enviar",
        // },
        // notificacao: {
        //     diasAtras: "dias atrás",
        //     hoje: "hoje",
        //     umaSemanaAtras: "1 semana atrás",
        //     duasSemanasAtras: "2 semanas atrás",
        //     tresSemanasAtras: "3 semanas atrás",
        //     quatroSemanasAtras: "4 semanas atrás",
        //     umMesAtras: "1 mês atrás",
        // },
        // notificacaoModal: {
        //     notificacaoLidaComSucesso: "Notificação lida com sucesso!",
        //     notificacoes: "Notificações",
        //     nenhumaNotificaçaoEncontrada: "Nenhuma notificação encontrada!",
        //     verTudo: "Ver tudo",
        //     verNotificacoes: "Ver notificações",
        // },
        // paginacao: {
        //     itensPorPagina: "Itens por página",
        //     20: "20",
        //     40: "40",
        //     60: "60",
        //     80: "80",
        // },
        // pauta: {
        //     comissao: "Comissão",
        //     analistaResponsavel: "Analista Responsável",
        // },
        // pautaAtaModoVisualizacao: {
        //     numeroSequencial: "Num. Seq.",
        //     comissao: "Comissão",
        //     analistaResponsavel: "Anal. Resp.",
        //     data: "Data",
        //     nadaEncontrados: "Nada encontrado",
        //     tenteNovamenteMaisTarde: "Tente novamente mais tarde",
        // },
        // propostaDeAta: {
        //     codigoPpm: "Código PPM",
        //     tituloDaProposta: "Título da Proposta",
        //     responsavelDoNegocio: "Responsável do Negócio",
        //     problema: "Problema",
        //     proposta: "Proposta",
        //     beneficios: "Benefícios",
        //     frequenciaDeUso: "Frequência de Uso",
        //     custos: "Custos",
        //     custosAqui: "Custos aqui",
        //     periodoDeExecucao: "Período de Execução",
        //     paybackSimples: "Payback Simples",
        //     linkDoJira: "Link Do Jira",
        //     anexos: "Anexos",
        //     parecerComissao: "Parecer Comissão",
        //     aprovado: "Aprovado",
        //     reprovado: "Reprovado",
        //     maisInformacoes: "Mais Informações",
        //     businessCase: "Business Case",
        //     aprovado: "Aprovado",
        //     escrevaNovaInformacao: "Escreva a nova informação...",
        //     parecerDG: "Parecer DG",
        //     aprovado: "Aprovado",
        //     reprovado: "Reprovado",
        // },
        // responsavelNegocio: {
        //     responsavelDoNegocio: "Responsável do negócio",
        //     insiraResponsavelDoNegocio: "Insira o responsável pelo negócio...",
        //     area: "Área",
        //     insiraAreaDoResponsavel: "Insira a área do responsável...",
        // },
        // userModal: {
        //     normal: "Normal",
        //     pequeno: "Pequeno",
        //     muitoPequeno: "Muito Pequeno",
        //     grande: "Grande",
        //     muitoGrande: "Muito Grande",
        //     configuracoes: "Configurações",
        //     escopos: "Escopos",
        //     chats: "Chats",
        //     A: "A",
        //     modoClaroEscuro: "Modo Claro/Escuro",
        //     sair: "Sair",
        // },
        // chat: {
        //     pesquisarPorNome: "Pesquisar por nome...",
        //     usuario: "Usuário",
        //     selecioneAlgumaConversa: "Selecione alguma conversa",
        //     encerrarChat: "Encerrar chat",
        //     escrevaSuaMensagem: "Escreva sua mensagem...",
        //     enviarAnexo: "Enviar anexo",
        //     enviarMensagem: "Enviar mensagem",
        // },
        // detalhesAta: {
        //     ataCriadaComSucesso: "Ata criada com sucesso!",
        //     ata: "Ata",
        //     numeroSequencial: "Número Sequencial",
        //     data: "Data",
        //     inicio: "Início",
        //     fim: "Fim",
        //     sumario: "Sumário",
        //     proposta: "Proposta",
        //     voltar: "Voltar",
        //     proximo: "Próximo",
        //     publicar: "Publicar",
        // },
        // detalhesDemandaPagina: {
        //     tour: {
        //         tour1: "Essa é a página de detalhes da demanda. Aqui você pode ver todos os detalhes da demanda selecionada.",
        //         tour2: "Cicando aqui, você consegue baixar em PDF essa demanda.",
        //         tur3: "Clicando neste lápis, você consegue estar editando as informações.",
        //     }
        // },
        // detalhesPauta: {
        //     pauta: "Pauta",
        //     numeroSequencial: "Número Sequencial",
        //     ano: "Ano",
        //     sumario: "Sumário",
        //     proposta: "Proposta",
        //     voltar: "Voltar",
        //     proximo: "Próximo",
        //     criarAta: "Criar Ata",
        // },
        // escopos: {
        //     tour: {
        //         tour1: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
        //         tour2: "Aqui fica os escopos criados automaticamente, em cada escopo é possível abrir novamente para edição. É criado um escopo para cada projeto que você abre e não finaliza.",
        //         tour3: "Nesta área você consegue visualizar qual a porcentagem preenchida do formulário.",
        //         tour4: "Clicando na lixeira você exclui o escopo.",
        //     },
        //     pesquisarPorTitulo: "Pesquisar por título...",
        //     pesquisar: "Pesquisar",
        //     escopoDeletadoComSucesso: "Escopo deletado com sucesso!",
        // },
        // home: {
        //     tourAjuda: {
        //         barraDePesquisa: "Aqui fica a barra de pesquisa, onde você pode pesquisar por um título.",
        //         iconeOredenar: "Neste ícone você pode ordenar as suas demandas por título (A-Z ou Z-A), Score (Maior ao menor ou Menor ao maior) e pela data (Mais nova à mais velha ou Mais velha à Mais nova).",
        //         botaoFiltrar: "Neste botão você pode filtrar suas demandas por seus status.",
        //         modoVisualizacao: "Nesta parte você pode trocar o modo de visualização das suas demandas. Você pode escolher entre visualizar as demandas em forma de lista ou em forma de cards.",
        //         criarNovaDemanda: "Aqui você consegue iniciar a criação de uma nova demanda.",
        //         areaDemanda: "Nesta área você consegue observar suas demandas. Você pode clicar em uma demanda para ver mais detalhes.",
        //         statusDemanda: "Nesta área você consegue visualizar o status atual da demanda.",
        //         botaoMotivo: "Aqui consegue observar o motivo pelo qual foi recusado ou o motivo da edição.",
        //     },
        //     demandaCriadaComSucesso: "Demanda criada com sucesso!",
        //     minhasDemandas: "Minhas Demandas",
        //     meuDepartamento: "Meu Departamento",
        //     visualizacaoEmTabela: "Visualização em Tabela",
        //     visualizacaoEmBloco: "Visualização em Bloco",
        //     pesquisarPorTitulo: "Pesquisar por título...",
        //     pesquisar: "Pesquisar",
        //     ordenacao: "Ordenação",
        //     filtrar: "Filtrar",
        //     criarDemanda: "Criar Demanda",
        //     demandaTour: "Demanda Tour",
        //     esseUmExemploDeDemanda: "Esse é um exemplo de demanda",
        //     nomeDoSolicitante: "Nome do Solicitante",
        // },
        // homeGerencia: {
        //     toursDemandas: {
        //         tour1: "Aqui é a barra de pesquisa, você pode pesquisar por algum título de alguma demanda",
        //         tour2: "Esse é icone de ordenação, onde poderá ordenar os itens por ordem alfabética, por score ou por data de criação",
        //         tour3: "Aqui fica o filtro, podendo filtrar por: Solicitante, Gerente Responsável, Fórum, Departamento, Tamanho e número",
        //         tour4: "Aqui fica o lugar para exportar as demandas em formato de planilha",
        //         tour5: "Aqui pode iniciar o processo de criação de uma nova demanda",
        //         tour6: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes",
        //         tour7: "Clicando aqui você pode ver o histórico de alterações da demanda",
        //         tour8: "Nesta área você pode visualizar o status da demanda",
        //         tour9: "Clicando aqui você pode alterar o modo de visualização para tabela ou cards",
        //     },
        //     toursCriarPropostas: {
        //         tour1: "Nesta parte fica as demandas, podendo clicar em uma demanda para ver mais detalhes e/ou criar uma proposta",
        //         tour2: "Nesta área você pode visualizar o status da demanda",
        //         tour3: "Clique aqui para ver o histórico de alterações da demanda",
        //     },
        //     toursPropostas: {
        //         tour1: "Nesta parte fica as propostas, podendo clicar em uma proposta para ver mais detalhes.",
        //         tour2: "Clicando aqui você pode abrir o chat com o solicitante da demanda",
        //         tour3: "Clicando aqui você pode ver o histórico de alterações da proposta",
        //     },
        //     toursPautas: {
        //         tour1: "Nesta parte fica as pautas, podendo clicar em uma pauta para ver mais detalhes.",
        //         tour2: "Clicando aqui você pode excluir a pauta",
        //     },
        //     toursAtas: {
        //         tour1: "Nesta parte fica as atas, podendo clicar em uma ata para ver mais detalhes",
        //     },
        //     feedback: {
        //         feedback1: "Ata publicada com sucesso!",
        //         feedback2: "Demanda aceita com sucesso!",
        //         feedback3: "Demanda recusada com sucesso!",
        //         feedback4: "Demanda devolvida com sucesso!",
        //         feedback5: "Proposta criada com sucesso!",
        //     },
        //     demandas: "Demandas",
        //     criarPropostas: "Criar Propostas",
        //     propostas: "Propostas",
        //     pautas: "Pautas",
        //     atas: "Atas",
        //     visualizacaoEmTabela: "Visualização em tabela",
        //     visualizacaoEmBloco: "Visualização em bloco",
        //     pesquisarPorTitulo: "Pesquisar por título...",
        //     filtrar: "Filtrar",
        //     exportar: "Exportar",
        //     criarDemanda: "Criar Demanda",
        //     demandaParaTour: "Demanda para Tour",
        // },
        // login: {
        //     email: "Email",
        //     senha: "Senha",
        //     esqueciSenha: "Esqueci a senha",
        //     entrar: "Entrar",
        //     feedback: {
        //         dadosInvalidos: "Dados inválidos!",
        //         preenchaTodosOsCampos: "Preencha todos os campos!",
        //     },
        // },
        // notFound: {
        //     pageNotFound: "Page Not Found",
        //     desculpePaginaNaoEncontrada: "Desculpe, a página informada não foi encontrada!",
        //     porfavorVolteParaPaginaPrincipal: "Por favor, volte para a página principal.",
        //     voltar: "Voltar",
        // },
        // notificacao: {
        //     notificacaoMArcadasComoNaoLidasComSucesso: "Notificações marcadas como não lidas com sucesso!",
        //     notificacaoMArcadasComoLidasComSucesso: "Notificações marcadas como lidas com sucesso!",
        //     notificacaoExcluidasComSucesso: "Notificações excluídas com sucesso!",
        //     notificacoes: "Notificações",
        //     deletar: "Deletar",
        //     marcarComoLido: "Marcar como lido",
        //     tipo: "Tipo",
        //     titulo: "Titulo",
        //     data: "Data",
        //     marcarComoNaoLido: "Marcar como não lido",
        //     marcarCommoLido: "Marcar como lido",
        //     deletar: "Deletar",
        //     naoHaNotificacoes: "Não há notificações",
        // },




    } : linguagem == "ch" ? {
        linguagem: "ch",
       
    } : null;
}

export default TextLanguage;